.prettierignore
.travis.yml
package.json
packages/cli/.prettierignore
packages/cli/package.json
packages/core/.prettierignore
packages/core/package.json
packages/schema/.prettierignore
packages/schema/docs/build/schema.md
packages/schema/exported-schema.json
packages/schema/package.json
yarn.lock

The actual content of this is:
* remove `prettier` from devDeps (stays in cli since it's used in scaffold)
* remove `husky`, `lint-staged`, and their configuratioon from all packages
* per [the docs](https://github.com/typicode/husky/blob/master/DOCS.md#multi-package-repository-monorepo), only run husky in the root. 
the exported schema json got run through prettier again and the formatting changed. we jumped a number of minor versions, so something must have changed. In any case, stepped through the command and confirmed that what's in this PR is the output of `prettier` `v1.18.2`, so ¯\\\_(ツ)_/¯

centralize husky code

---

packages/legacy-scripting-runner/package.json

Adds fake AWS keys in the test command so we don't have to add them in Travis.

Add fake AWS keys to legacy-scripting-runner test command

---

packages/core/src/tools/create-callback-wrapper.js
packages/core/test/create-app.js
packages/core/test/tools/callback-wrapper.js

For callbacks to work, we need to pull the `callback_url` out of the `event` (see [here](https://github.com/zapier/zapier/blob/5582e64027858bfd54010e72be3246be8625af21/web/backend/zapier/developer_cli/api_base.py#L860). There was a typo that prevented this from working as expected.

fix finding callback url in event correctly

---

packages/legacy-scripting-runner/bundle.js
packages/legacy-scripting-runner/test/bundle.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js
packages/schema/docs/build/schema.md

Fixes another issue in [PDE-1078](https://zapierorg.atlassian.net/browse/PDE-1078). For operations (triggers and searches) that default to a GET request, `bundle.request.data` should exactly be `null` instead of an empty object in their scripting methods (`pre_poll`, `pre_search`, etc).

bundle.request.data should be null for GET requests

---

package.json
packages/schema/docs/build/schema.md
packages/schema/examples/definition.json
packages/schema/exported-schema.json
packages/schema/lib/schemas/BasicOperationSchema.js
packages/schema/lib/schemas/RefResourceSchema.js

This brings the `contact.id.firstName,lastName` dynamic dropdown pattern to CLI! I've confirmed it works:
`contact.id.lastName,firstName,lastName`: 
This involves couple of changes:
1. change `resource` property to `KeySchema` since `dynamic: 'contact'` is an error in the editor
2. That allows us to make more assertions about the shape of actual references, which needs the shape `x.y(.z)?`. We also now include an optional comma clause (but only 1, I got nervous the regex would get unwieldy. We could also simplify it and just allow commas anywhere, but I worry someone will mess it up and it'll be very unclear why their dynamic dropdown isn't working)
Very strictly speaking, this is a semver.major since before it was valid to have `dynamic: 'x'` and on this version, it won't be. That said, …

[schema] Allow RefResources to have commas in the labels

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/integration-test.js

We need to cover the functionality in python, which returns empty dicts if an empty list or null value is provided.

fix(legacy-scripting-runner): add object-first flag to runCreate

---

packages/core/bin/build-boilerplate.sh

Makes it easier to build boilerplate from published packages. This allows us to patch existing core boilerplate with the latest legacy-scripting-runner release.
Usage: `yarn build-boilerplate -- production`

chore(core): allow to build boilerplate from published packages

---

packages/cli/src/oclif/commands/login.js
packages/cli/src/tests/utils/api.js
packages/cli/src/tests/utils/credentials.js
packages/cli/src/utils/credentials.js

Duplicates https://github.com/zapier/zapier-platform-cli/pull/420. The salient change is that users can paste a deploy key instead of typing an email or password. if we know they're a SAML user based on their email, we can force them into that flow. Otherwise, the experience is the same.

feat(cli): add saml support

---

packages/schema/docs/build/schema.md
packages/schema/exported-schema.json
packages/schema/lib/functional-constraints/index.js
packages/schema/lib/functional-constraints/labelWhenVisible.js
packages/schema/lib/schemas/BasicDisplaySchema.js
packages/schema/test/functional-constraints/labelWhenVisible.js
packages/schema/test/utils.js

Noticed the other day that hidden triggers needed label/description. This loosens that requirement. 
The one thing I still need to test is that the editor plays nicely with this. I'll do that before I merge it.

fix(schema): Make label & description optional for hidden actions

---

packages/legacy-scripting-runner/bundle.js
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/bundle.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

Fixes three bugs:
1. `bundle.raw_url` should be available for `KEY_(pre|post)_custom_X_fields` methods and have the original curly variables, such as `https://example.com/things/{{object_id}}` instead of `https://example.com/things/{{bundle.inputData.object_id}}`.
2. Underscore `_.template` should use `{{...}}` instead of the default `<% ... %>`.
3. The request object returned from a `KEY_pre` should be combined with `bundle.request` afterward. That means returning an empty object is equivalent to returning `bundle.request`.

fix(legacy-scripting-runner): bundle.raw_url, _.template, and request fallback

---

docs/cli.html
docs/cli.md
package.json
packages/cli/docs/cli.html
packages/cli/docs/cli.md
packages/cli/package.json
packages/cli/src/bin/docs.js
packages/cli/src/commands/help.js
packages/cli/src/oclif/ZapierBaseCommand.js
packages/cli/src/oclif/commands/apps.js
packages/cli/src/oclif/commands/history.js
packages/cli/src/oclif/commands/init.js
packages/cli/src/oclif/commands/login.js
packages/cli/src/oclif/commands/logout.js
packages/cli/src/oclif/commands/versions.js

We [noticed](https://zapier.slack.com/archives/C5Z9BP4U9/p1570028316375200) that the slack invite url was expired. I fixed it in master (https://github.com/zapier/zapier-platform/commit/74711f04f3bf1832f259387510e066f87cac24b8), and as a result, noticed that `cli.docs` wasn't getting run in the pre-commit. 
That's fixed here, plus adding code to format the command into markdown (so it's picked up by the `docs` command). 
This code was simplified from [@oclif/plugin-help](https://github.com/oclif/plugin-help/blob/master/src/command.ts), which we use. It would have been cool to be able to use the formatting functions without their `bold` and joining and stuff, so that's maybe a PR i'll make at some point. In any case, this is good for now.

docs(cli) add new commands to docs

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

Fixes three `KEY_pre_write` bugs dealing with file upload:
* Developers can set an arbitrary `Content-Type` request header in `KEY_pre_write`, we should correct it to `multipart/form-data` no matter what.
* If `request.data` returned by `KEY_pre_write` is an object, we should separate each field in the multipart request instead of serializing them into a `data` field as a JSON string.
* We should allow developers to rename a file field in `KEY_pre_write`.
For more detail, see the newly-added test cases.

fix(legacy-scripting-runner): fix file upload issues

---

docs/index.html
packages/cli/README.md
packages/cli/docs/index.html
packages/cli/snippets/input-fields-children.js

Resolves https://github.com/zapier/zapier-platform/issues/81 by removing the `required` property line from the parent field in the affected snippet.

fix(cli): Remove required property from parent field in line-items snippet

---

packages/cli/src/oclif/commands/validate.js
packages/cli/src/utils/display.js

Adopts the new response format of `/api/platform/cli/check`, which was changed by https://github.com/zapier/zapier/pull/31726.

fix(cli): update to latest format of validate endpoint

---

packages/cli/src/constants.js
packages/cli/src/oclif/ZapierBaseCommand.js
packages/cli/src/tests/baseCommand.js
packages/cli/src/tests/testing.js
packages/cli/src/tests/utils/analytics.js
packages/cli/src/utils/analytics.js
packages/cli/src/utils/api.js
packages/cli/src/utils/build.js
packages/cli/src/utils/convert.js

I noticed a big surge of analytics on `linux` with odd behavior, such as no command (which should never be possible). Turns out the culprit was traivs. Fixed some minor bugs while I was in there.

fix(cli): don't run analytics during tests

---

packages/core/src/http-middlewares/after/throw-for-stale-auth.js
packages/core/src/http-middlewares/after/throw-for-status.js
packages/core/src/tools/http.js

URL querystring may contain sensitive data so shouldn't be shown in the error message.
Fixes https://github.com/zapier/zapier/issues/32319.

fix(core): hide sensitive data from error messages

---

packages/core/smoke-test/smoke-test.js

Minor test fixes to make it easier to run smoke tests locally.
Also disables analytics from running in the tests, but doesn't actually work because of the bug fixed in #84 (that isn't deployed yet)

test(core): fix for analytics in tests & cleanup

---

example-apps/babel/package.json
example-apps/basic-auth/package.json
example-apps/create/package.json
example-apps/custom-auth/package.json
example-apps/digest-auth/package.json
example-apps/dynamic-dropdown/package.json
example-apps/files/package.json
example-apps/github/package.json
example-apps/middleware/package.json
example-apps/minimal/package.json
example-apps/oauth1-trello/package.json
example-apps/oauth1-tumblr/package.json
example-apps/oauth1-twitter/package.json
example-apps/oauth2/package.json
example-apps/resource/package.json
example-apps/rest-hooks/package.json
example-apps/search-or-create/package.json
example-apps/search/package.json
example-apps/session-auth/package.json
example-apps/trigger/package.json
example-apps/typescript/package.json
packages/legacy-scripting-runner/$.js
packages/legacy-scripting-runner/package.json
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js
yarn.lock

Adds support for more jQuery functions.
Also updates yarn.lock and core versions for example apps.

fix(legacy-scripting-runner): add more jquery functions

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

legacy-scripting-runner should clean headers just as Web Builder [does it](https://github.com/zapier/zapier/blob/0b95996f00238b3e092547a1478e4dc23972c5de/web/backend/zapier/useful/request_extras.py#L505).

fix(legacy-scripting-runner): clean headers like legacy WB

---

packages/schema/lib/constants.js
packages/schema/lib/functional-constraints/mutuallyExclusiveFields.js
packages/schema/test/functional-constraints/mutuallyExclusiveFields.js

As part of https://github.com/zapier/zapier/pull/32518, I noticed that the frontend could get into a bad state where it was sending `{dict: false, list: false}` and schema was complaining that those were mutually exclusive. 
We can be a little more permissive here- it's only bad if they're truthy. My one unknown is that I'm not sure how the editor reads these values. If it also uses `_.has`, then this will cause weird behavior. @stevelikesmusic that's what I wanted to loop you in on if you could double check.

fix(schema) be a little more permissive with mutually exclusive fields

---

packages/legacy-scripting-runner/bundle.js
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

We replace `{{var}}` in URLs with `{{bundle.authData.var}}` or `{{bundle.inputData.var}}` when converting a WB app. This breaks developers' scripting code if they assume `{{var}}` is still in URLs. To fix, we should undo the replacement before passing the bundle to developers' scripting code.

fix(legacy-scripting-runner): fix curly replacement

---

docs/cli.html
docs/cli.md
packages/cli/docs/cli.html
packages/cli/docs/cli.md
yarn.lock

I found in our local dev, `zapier-platform/node_modules/lodash` was always 4.17.11 even though we bumped it to 4.17.15. I had to delete `yarn.lock` and rebuild a new one for yarn to correctly resolve Lodash to 4.17.15.

chore: rebuild yarn.lock

---

packages/core/CHANGELOG.md
packages/schema/CHANGELOG.md

update links in changelog.md for core and schema to platform repository (archived cli repository has changelog up to 8.2.1)

docs(core,schema) update changelog.md links to point to zapier-platform repository

---

packages/cli/src/oclif/commands/validate.js
packages/cli/src/utils/api.js
packages/cli/src/utils/build.js

We were still using `/style-check` for the api call that happens during the `build` validation step. We should combine these at some point, but for now it's ok.

fix(cli) Run validation during build against `/check` endpoint

---

docs/index.html
packages/cli/README.md
packages/cli/docs/index.html
packages/cli/snippets/mocha-test.js

 docs(cli) fix double `App.App.` in unit test snippet

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

Fixes an issue where we allow an action URL to return `204 no content` or a non-JSON data in the legacy platform.

fix(legacy-scripting-runner): allow legacy actions to return non-json data

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/middleware-factory.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/example-app/oauth2.js
packages/legacy-scripting-runner/test/integration-test.js

Legacy Web Builder apps can use placeholders like `{{client_id}}` and `{{client_secret}}` for their OAuth2 client ID and secret to allow users to fill in their own values. This PR enables converted apps to do that too.
Note: WB doesn't have this ability for OAuth1. But since it's easy, I also added the feature for OAuth1 in this PR on the way.
Works with https://github.com/zapier/zapier/pull/34255.

feat(legacy-scripting-runner): support for dynamic OAuth client ID and secret

---

example-apps/typescript/package.json
yarn.lock

implement `zapier-clean` step on `zapier-build` as some files can remain in `lib`/`build` folders after deleting/renaming source `.ts` files
PS
I'm not sure why are there this much changes in `yarn.lock` file (just running `yarn install` on master branch generates some changes to this file)

fix(example) implement zapier-clean script

---

example-apps/typescript/tsconfig.json
packages/core/index.d.ts

* use NodeJS.ReadableStream instead of ReadableStream from DOM
* set node tsconfig [recommended settings](https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping) for node 10.x in example app
* explicitly provide only es2018 lib in tsconfig (to avoid accidental importing of DOM modules)

fix(core) use NodeJS ReadableStream instead of DOM in TS definitions

---

packages/cli/scaffold/convert/package.template.json

Originally `zapier convert` generates a `package.json` that pinpoints Node version to 8.10, which creates a minor inconvenience because developers need to manually edit`package.json` to fix it. This PR saves that trouble.

fix(cli): allow Node version >= 10 in package.json generated by `zapier convert`

---

packages/cli/src/utils/example-apps.js

Previously, all versions of the CLI pulled from the master branch when making example apps. This was good because we could fixes to the example apps would be available right away. Less good because example apps might conflict with released versions of the CLI.
This came to a head when I merged https://github.com/zapier/zapier-platform/pull/124 and the build broke. Two main issues:
* Part of the build is calling `zapier init --template typescript` and `zapier build`. Now, this test was running using the master branch's `typescript` template but published `core@9.0.0`. Because that PR changed the TS configuration, the definitions in core were incompatible and it threw an error.
* apparently CI isn't run on PRs of forks. There's [good …

fix(cli) tie example apps to package version

---

packages/core/src/http-middlewares/before/add-basic-auth-header.js
packages/core/test/http-middleware.js

In Web Builder, we allow username or password to be empty. For example, a developer can use an auth mapping like the following to do basic-auth-backed API key auth:
```
{
"username": "{{api_key}}",
"password": ""
}
```
In CLI core, however, we currently require both username and password to be non-empty for the basic auth middleware to add the auth header to the request. This causes trouble if we convert a WB app like that to CLI. Not sure why we did that in the first place, but I think it should be good if we allow either username or password to be empty.

fix(core): don't require both username and password for basic auth

---

docs/cli.html
docs/cli.md
packages/cli/docs/cli.html
packages/cli/docs/cli.md
packages/cli/src/oclif/ZapierBaseCommand.js
packages/cli/src/oclif/commands/validate.js
packages/cli/src/utils/display.js

Addresses [PDE-1251](https://zapierorg.atlassian.net/browse/PDE-1251).
Before:
After:

style(cli): make language of validate command consistent with UI

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

* If custom fields came back as a non-array, return an empty array.
* If a custom field is not an object or doesn't have a `key`, skip it.

fix(legacy-scripting-runner): more defensive about custom fields

---

packages/legacy-scripting-runner/bundle.js
packages/legacy-scripting-runner/test/bundle.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

`bundle.load` should be the same as `bundle.request.data` for pre_oauthv2_token` and `pre_oauthv2_refresh`.

fix(legacy-scripting-runner): convert bundle.load correctly for oauth2

---

packages/core/bin/build-boilerplate.sh
packages/core/bin/update-boilerplate-dependencies.js

Just a tooling improvement. This allows us to specify a zapier-platform-core version on npm when building a boilerplate zip. Example usage:
```
./bin/build-boilerplate.sh production 9.0.0
```

chore(core): allow to specify core version when building a boilerplate

---

packages/cli/src/tests/utils/convert.js
packages/cli/src/utils/convert.js

fix(cli): convert command crashes over a trailing comment

---

package.json
scripts/bump.js
yarn.lock

Part of [PDE-870](https://zapierorg.atlassian.net/browse/PDE-870) to fix our currently broken release process.
Originally, we used `lerna version`, which doesn't fit our needs entirely and isn't easy to customize. So I ended up manually editing `package.json`s and adding git tags a lot when releases packages.
This PR adds a standalone and interactive script `./scripts/bump.js` (can also be executed with `yarn bump`), which does the following things:
1. ask us which package(s) and the version(s) to bump
2. bump the selected packages by editing their `package.json`
3. update example apps' dependencies in `package.json`
4. git commit the changes
5. add the necessary git tags
Once the script finished, the only thing we need to do is to `git push origin master --tags`. When Travis CI sees the …

tooling: custom bump script

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

Using `this.something` in a scripting method should equivalent to `Zap.something`.

fix(legacy-scripting-runner): 'this' should be bound to 'Zap'

---

packages/core/src/http-middlewares/before/add-digest-auth-header.js
packages/core/test/http-middleware.js

fixes the problem described [here](https://zapier.slack.com/archives/C5Z9BP4U9/p1580763373284900)
it doesn't look like we've got any testing here, which is why this may have gone undetected so long? I'm also puzzled at why this would have worked at all recently and only broke when we did the godzilla core 8 -> upgrade. In any case, this will fix the issue.

fix(core): add `new` to url call

---

packages/schema/docs/build/schema.md
packages/schema/exported-schema.json
packages/schema/lib/schemas/FieldSchema.js

You wouldn't know for sure from reading the original description what this meant for output fields, so I wanted to be more explicit about it

docs(schema): Clarify FieldSchema.list for input v output fields

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

fix(legacy-scripting-runner): stop immediately when scripting method errors

---

packages/legacy-scripting-runner/$.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

Allows to use jQuery `$.each` in legacy scripting.

fix(legacy-scripting-runner): add support for jquery $.each

---

packages/cli/src/oclif/commands/login.js

The link previously contained a trailing comma which is attached to the URL when selected.
Previously this was routing to [https://zapier.com/developer/partner-settings/deploy-keys/,](https://zapier.com/developer/partner-settings/deploy-keys/,) which goes to 404.
This has been updated to go to [https://zapier.com/developer/partner-settings/deploy-keys/](https://zapier.com/developer/partner-settings/deploy-keys/)
The previous text looked like:
```
zapier login --sso
Your /Users/calebfroese/.zapierrc has not been set up yet.
To generate a deploy key, go to https://zapier.com/developer/partner-settings/deploy-keys/, create/copy a key, and then paste the result below.
? Paste your Deploy Key here:
```
Which now looks like
```
zapier login --sso
Your /Users/calebfroese/.zapierrc has not been …
```

fix(cli): Fix the SSO login link

---

packages/legacy-scripting-runner/bundle.js
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

In Web Builder, there's a "Send in Action Endpoint URL in JSON body" checkbox for each action field:
Currently, legacy-scripting-runner respects this checkbox for `bundle.request.data` but not for `bundle.action_fields`. Action fields that disable this option (unchecked) shouldn't go to `bundle.action_fields` but still appear in `bundle.action_fields_full` and bundle.action_fields_raw`.

fix(legacy-scripting-runner): exclude a field from bundle.aciton_fields if "Send in JSON body" is unchecked

---

packages/legacy-scripting-runner/$.js
packages/legacy-scripting-runner/test/example-app/index.js

Allows jQuery `$.each` to have a second argument. Example:
```js
var arr = ['a', 'b', 'c'];
$.each(arr, function(index, item) {
// ...
});
```

fix(legacy-scripting-runner): $.each should accept an array element at second arg

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

Change header code to be a little more defensive around calling `.replace`

fix(legacy-scripting-runner) non-string-like headers shouldn't blow up

---

packages/core/index.d.ts
packages/core/package.json
yarn.lock

Per discussion in [this comment](https://github.com/zapier/zapier-platform/issues/8#issuecomment-591877355), tweaking the types for `appTester` so it accepts perform methods that are synchronous.
In addition to changing the output type of `perform`, I simplified what `appTester` itself returns, since it always returns a promise. This is safe because there was a logic error before and it always evaluated to `Promise<T>` anyway. You can test that in [the playground](https://www.typescriptlang.org/play/#code/C4TwDgpgBA5hB2EBOBLAxgMQK7zVAvFADwAqAfABQCGSMAXFCQJQFmNQQAewCAJgM5QACkgD2AWxT8IpNgH4o-YKngwoDeFnEAjZAG4AUAbSj4SqCdEAbBnESpMOPIQrAAFilUMq8EC3xs7p4wRgD0oVDioljSUKIAbsgcVGhuUAAGllbpUJ7xomhUwCimADRQ7tBIEMBYSPAV4NBSUFRWAO5UIILpmjrI6QbhrYIAZjQjUACSFj4VEFZW5ZXVAOSC8KK58GBYwBVuRVCHglRQ1bX1jZAZSio …

fix(core) improve `appTester` types and bump node versions

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/package.json
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js
yarn.lock

Allows `post_oauthv2_token` to return nothing and default to the response content.
Also updates the core dependency for legacy-scripting-runner.

fix(legacy-scripting-runner): allow post_oauthv2_token to return nothing

---

packages/cli/src/smoke-tests/smoke-tests.js
packages/core/smoke-test/smoke-test.js
packages/schema/smoke-test/smoke-test.js
scripts/bump.js

Addresses [PDE-1318](https://zapierorg.atlassian.net/browse/PDE-1318).
There's a cyclic dependency in our release process:
1. `yarn bump` bumps example apps' core version
2. core's smoke tests do live `npm install` on the example apps. Since the new core version hasn't published to npm yet, the install would fail.
3. To successfully `npm publish`, smoke tests must pass. But smoke tests couldn't pass because of 2.
This PR addresses 2 so core's smoke tests no longer download the new core version from npm.
There are some minor changes. I'll annotate them in the comments.

refactor(core): fix smoke test cyclic dependency

---

packages/legacy-scripting-runner/bundle.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

When catching a hook, we should pass `bundle.rawRequest` to `KEY_catch_hook` as `bundle.request`.

fix(legacy-scripting-runner): pass through bundle.rawRequest for hooks

---

packages/legacy-scripting-runner/index.js

Every time a scripting method is run, log the converted bundle for debugging.

feat(legacy-scripting-runner): log converted bundles

---

packages/cli/src/oclif/commands/env/set.js

fix(cli): Correctly parse out env variables that contain an equal sign
Fixes a bug where we don't correctly parse env variables that contain an equal sign as part of the variable. An equal sign is a valid special character and occurs reasonably often in things such as CLIENT_SECRETS, etc. This seems to be a regression as the previous `env` command didn't parse those incorrectly.

Allow env variables containing equals

---

packages/core/src/tools/cleaner.js
packages/core/test/create-request-client.js

fix(core): Preserve values that also include empty curlies in request body
Fixes a bug where we expect `body: { partial: 'text {{123__unresolved_curly}}' } }` to include `'text'` in the value sent to the API. 
Instead we were removing the whole field from the request if we found an unresolved curly. This fix preserves the hardcoded value so that:
```js
body: { partial: 'text {{123__unresolved_curly}}' } }
// becomes
body: { partial: 'text' } }
```

Preserve values that also include empty curlies

---

packages/legacy-scripting-runner/$.js
packages/legacy-scripting-runner/package.json
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js
yarn.lock

Fixes [PDE-1357](https://zapierorg.atlassian.net/browse/PDE-1357).
We've been using `cheerio` and `jquery-param` for a lighter alternative for `jquery` and `jsdom`. But we found it hard to recreate identical jQuery capabilities this way. This PR includes `jquery` and `jsdom` back to dependencies and removes `cheerio` and `jquery-param`. There's a new test case demonstrating a common usage of jQuery DOM manipulation, which is hard to replicate if we do it on our own.
After adding this, the boilerplate zip will grow from 3.3 MB to 4.7 MB.

fix(legacy-scripting-runner): full jQuery support

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

If the response is an error (status code >= 400), Web Builder would call the `post` method then raise an exception for the error response.
But legacy-scripting-runner is doing it differently: It raises an exception without calling the post method. This PR fixes that.

fix(legacy-scripting-runner): run post method first before throwing response status error

---

scripts/bump.js
scripts/publish.sh

Fixes https://travis-ci.com/github/zapier/zapier-platform/builds/155448960#L1293, an issue I ran into when releasing 9.2.0. We'll test it again if it works next time we release a new version.
Also changes the bump script so we can only bump either `cli/core/schema` or `legacy-scripting-runner`. Bumping both doesn't really work. `legacy-scripting-runner` would have to wait until the new version of `core/schema` to be published but we aren't doing that.

tooling(boilerplate): wait for schema to be published when building boilerplate

---

packages/core/src/tools/cleaner.js
packages/core/test/create-request-client.js

We've seen many developers getting confused by the error message `Cannot reliable interpolate objects or arrays into a string`. It can be hard to figure out which trigger or action is having an issue without knowing the variable being resolved.
This PR changes the error message from:
```
Cannot reliable interpolate objects or arrays into a string. We received an Array:
"1,2,3"
```
to
```
Cannot reliable interpolate objects or arrays into a string. Variable `bundle.inputData.foo` is an Array:
"1,2,3"
```

fix(core): show variable name in curlies type error

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html
packages/core/index.d.ts
packages/core/src/errors.js
packages/core/src/http-middlewares/after/throw-for-stale-auth.js
packages/core/src/http-middlewares/after/throw-for-status.js
packages/core/src/tools/create-lambda-handler.js
packages/core/src/tools/http.js
packages/core/src/tools/promise.js
packages/core/test/create-app.js
packages/core/test/errors.js
packages/core/test/tools/promise.js
packages/legacy-scripting-runner/exceptions.js

This adds `z.errors.Error` (`AppError`) and `z.errors.ResponseError` and uses the latter in `throwForStatus` and `throwForStaleAuth`.
- **JIRA:** `SXP-1286` [Create new Node z.errors classes](https://zapierorg.atlassian.net/browse/SXP-1286) and `SXP-1294` [Use new Node z.errors in throwForStatus](https://zapierorg.atlassian.net/browse/SXP-1294)
- **Spec:** https://github.com/zapier/sandbox-integration-errors/issues/6
The `z.error.Error` class is for developers to use instead of `Error` and takes an optional second `code` (string) and third `status` (number) argument. All arguments are `JSON.stringify`-ed as the message of the error. 
In [Python-land](https://github.com/zapier/zapier/blob/e03c532d97e4e647f44038eb5a35ce4b30de2b48/web/backend/zapier/developer_cli/api_base.py#L1114-L1126) we …

feat(core): New error classes that support error codes and statuses

---

packages/core/src/http-middlewares/before/prepare-request.js
packages/core/src/tools/cleaner.js
packages/core/test/create-request-client.js
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js
packages/schema/docs/build/schema.md
packages/schema/exported-schema.json
packages/schema/lib/schemas/RequestSchema.js

Addresses [PDE-1468](https://zapierorg.atlassian.net/browse/PDE-1468).
A common error of a converted app is:
"Cannot reliably interpolate objects or arrays into a string"
This is because the app uses curlies in their polling/action URL and the variable in the curlies is an array, such as `https://example.com?param={{an_array_variable}}`. Web Builder would replace `{{an_array_variable}}` with a comma-separated string such as `a,b,c`. But in VB, since core 8.0.0 with this breaking change (https://github.com/zapier/zapier-platform-core/pull/139), that syntax is no longer supported and would raise an error.
We've been advising partners to adjust code on their side. But there are just too many of them for us to handle it efficiently. I think to fix it, we can add an optional option …

feat(core,schema,legacy-scripting-runner): allow to "reliably interpolate arrays or objects to a string"

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

Addresses [PDE-1467](https://zapierorg.atlassian.net/browse/PDE-1467).
When converting a WB app, we replace "unbounded" curlies `{{var}}` in URLs with "bounded" curlies, which are either:
- `{{bundle.authData.var}}`
- `{{bundle.inputData.var}}`
- `{{process.env.var}}`
Which one to use is decided based on the field definition. That is, if `var` is in auth fields, then we replace `var` with `bundle.authData.var`.
The idea was to be explicit about variable referencing. But unfortunately, being explicit requires some guessing and is not always reliable. This PR adds support for unbounded curlies, so `{{var}}` in URLs will be still `{{var}}`. legacy-scripting-runner will do the implicit variable referencing as WB does.
Existing converted apps that are still using bounded curlies like …

feat(legacy-scripting-runner): support for unbounded curlies

---

packages/legacy-scripting-runner/CHANGELOG.md

Adds changelog for legacy-scripting-runner. Didn't go way back to the beginning because I'm not sure if that will be useful. We can trace back further if we want to.

docs(legacy-scripting-runner): add changelog

---

packages/core/src/http-middlewares/before/prepare-request.js
packages/core/src/tools/fetch.js
packages/core/test/create-request-client.js
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

Adds a hidden option `allowGetBody` to `z.request()`. When `allowGetBody` is true, `z.request` won't delete the body for the GET request. This is to add support for WB's ability to send GET requests with a body.
This has to be done with a nasty hack because node-fetch explicitly [forbids](https://github.com/node-fetch/node-fetch/blob/v2.6.0/src/request.js#L75-L78) us to send a GET request with a body (see also https://github.com/whatwg/fetch/issues/551). Not an ideal solution, but it gets the job done.

feat(core,legacy-scripting-runner): allow GET requests to have body

---

docs/index.html
example-apps/babel/src/authentication.js
example-apps/basic-auth/authentication.js
example-apps/custom-auth/authentication.js
example-apps/digest-auth/authentication.js
example-apps/github/index.js
example-apps/oauth2/authentication.js
example-apps/onedrive/authentication.js
example-apps/onedrive/resources/base-item.js
example-apps/onedrive/resources/folder.js
example-apps/onedrive/utils.js
example-apps/session-auth/authentication.js
example-apps/typescript/src/authentication.ts
examples/auth/basic.js
examples/auth/custom.js
examples/auth/digest.js
examples/auth/oauth2.js
examples/auth/session.js
packages/cli/README.md
packages/cli/docs/index.html
packages/cli/snippets/manual-request.js
packages/cli/snippets/middleware.js
packages/cli/snippets/put.js

Updates example apps and snippets to demonstrate (and with that encourage) the use of `z.errors.Error` over `Error`.
**JIRA:** `SXP-1624` [Replace use of Error by z.errors.Error in examples and docs](https://zapierorg.atlassian.net/browse/SXP-1624)

docs(core): update examples to demonstrate z.errors.Error

---

packages/legacy-scripting-runner/package.json
yarn.lock

Upgrades `request`. This helps reduce boilerplate zip size from 4.7 to 4.2 MB.
Note: `request` is deprecated, we'll want to look for something else for the longer term.

chore(legacy-scripting-runner): upgrade request

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/integration-test.js

Following up on #190, there's still a case we need to handle for the `cannot reliably interpolate objects or arrays into a string` error. See the test for details.

fix(legacy-scripting-runner): reliably resolve array curlies from other triggers/actions/searches

---

packages/cli/src/utils/build.js

Adds some compression when creating `build.zip`. 
Using an app w/ `lodash` and `moment` as dependencies, the zip size went from `1.6M` -> `409K`, so that's promising!
I also tested with an app pushed to prod - everything worked normally. I didn't notice any difference in the app build time. 
Test suite was the exact same speed.

improvement(cli): Compress zip files more

---

packages/cli/src/tests/utils/changelog.js
packages/cli/src/utils/changelog.js

https://keepachangelog.com/en/1.0.0/ uses a format like so:
but our changelog utils only handled
So this commit just loosens up the restrictions a bit. :)

fix(cli): Allow for different changelog version formats

---

packages/legacy-scripting-runner/bundle.js
packages/legacy-scripting-runner/index.js

Originally, we're using field `request_data` as the function input for bundle logs, and function output and uncaught errors aren't being logged. This PR fixes that, so we use `input` and `output` fields for bundle logs. We're going to log uncaught errors in `error_message` as well.
While I was there, I also
- refactored the confusing `runEvent` code with `async/await`
- removed the unnecessary `bundle.response.request.input` passed into legacy scripting

feat(legacy-scripting-runner): more complete bundle logs and runEvent refactoring

---

.gitignore
docs/index.html
example-apps/github/index.js
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html
packages/cli/snippets/manual-request.js
packages/core/src/http-middlewares/after/throw-for-status.js
packages/core/test/http-middleware.js
packages/schema/docs/build/schema.md
packages/schema/exported-schema.json
packages/schema/lib/schemas/RequestSchema.js

- JIRA: `SXP-1622` [v3 like v1/2 should only throw for >= 400 and < 600](https://zapierorg.atlassian.net/browse/SXP-1622)
- Discussion: https://github.com/zapier/sandbox-integration-errors/issues/2#issuecomment-610691775
Includes tests, which we didn't have for `throwForStatus`.

BREAKING CHANGE(core): `throwForStatus()` only when status between 400 and 600

---

packages/core/src/http-middlewares/after/log-response.js
packages/core/test/http-middleware.js

Fixes `logResponse` middleware so we don't `JSON.stringify` a `FormData` object.
Passing a `FormData` object to request body is valid usage when you want to upload a file:
```js
const FormData = require('form-data')
const perform = async (z, bundle) => {
const form = new FormData();
form.append('filename', 'sample.txt');
form.append('file', getStreamSomewhere());
const response = await z.request({
url: 'https://...',
body: form
});
// ...
};
```
I notice the `logResponse` middleware would just `JSON.stringify` the `FormData` object and send it to our log server, which results in something like [this](https://cdn.zapier.com/storage/files/2244d52292eeb3cba00d0dbac55f70e9.txt). This does not make sense but fine for most cases, at least it doesn't crash. However, I found for certain stream …

fix(core): don't log request body when it's form data

---

packages/cli/src/oclif/ZapierBaseCommand.js
packages/cli/src/oclif/commands/delete/integration.js
packages/cli/src/oclif/commands/delete/version.js
packages/cli/src/oclif/commands/deprecate.js
packages/cli/src/oclif/commands/describe.js
packages/cli/src/oclif/commands/env/set.js
packages/cli/src/oclif/commands/env/unset.js
packages/cli/src/oclif/commands/migrate.js
packages/cli/src/oclif/commands/promote.js
packages/cli/src/oclif/commands/team/add.js
packages/cli/src/oclif/commands/team/remove.js
packages/cli/src/oclif/commands/users/add.js
packages/cli/src/oclif/commands/users/remove.js
packages/cli/src/utils/api.js
packages/cli/src/utils/build.js

The original purpose of this PR was to improve the experience of `build`, `upload`, and `push`. `build` shouldn't need login details or a linked app to work (helpful for scratch testing). Upload does need both of those things, but it should check for them before we try to `build` (fail fast and early). It also improves the error message for these operations so users have more clear guidance on how to fix their problem.
While I was in there, I took a pass at reducing the number of duplicate calls to `/check` we do. There were a number of places where multiple functions in a command would each separately verify whether or not the user was logged in and could access the app. As a result, we should have fewer HTTP calls happening and everything should feel snappier as a result!

improvement(cli): condense checks for present and valid credentials

---

.travis.yml
package.json
packages/cli/package.json
packages/core/package.json
packages/legacy-scripting-runner/package.json
packages/schema/package.json

Leverages Travis [Build Stages](https://docs.travis-ci.com/user/build-stages/) to run groups of tests in parallel.

ci: use Travis build stages to speed up tests

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

Web Builder allows search resource URL (or `post_read_resource`) to return an array. If the result is an array, WB would take the first item of the array and use that to hydrate the search results.
CLI doesn't allow that for `performGet`. `performGet` must return an object. This PR fixes it so that `performGet` always returns an object even if the resource URL (or `post_read_resource`) gives us an array.

fix(legacy-scripting-runner): allow post_read_resource to return array

---

packages/legacy-scripting-runner/middleware-factory.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js
packages/schema/docs/build/schema.md

In #195, we introduced `allowGetBody` as a `z.request` option. There's a bug. When the option is enabled, we always send an empty object as the request body. Depending on the server implementation, some could raise an error if they get a `{}` in a GET request's body. This PR fixes that so legacy-scripting-runner doesn't do that. Core will still do that (sends an empty-object request body), so we should fix it from core too. But given that legacy-scripting-runner is the only user of `allowGetBody`, we can fix it later.

fix(legacy-scripting-runner): prune body if allowGetBody and body is empty

---

packages/legacy-scripting-runner/test/example-app/api-key-auth.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/example-app/oauth2.js
packages/legacy-scripting-runner/test/example-app/session-auth.js
packages/legacy-scripting-runner/test/integration-test.js

Fixes https://github.com/zapier/zapier-platform/pull/210/files#r418914759, where some tests of legacy-scripting-runner aren't properly compiling function source in the app definition. This only fixes the tests and won't affect the library itself.

refactor(legacy-scripting-runner): some tests aren't compiling function source

---

packages/core/src/http-middlewares/before/prepare-request.js
packages/core/test/create-request-client.js

Fixes a bug with the `z.request` option `allowGetBody`, introduced in #195. The bug arises when `allowGetBody` is true and `body` is an empty object, `z.request` would send the empty object (encoded as `{}` in JSON) along with the GET request. This could break when the target server isn't expecting an empty object in a GET request. The newly-added test should be self-explanatory.
While I was there, I changed the test endpoint from postman-echo to the new echo endpoint of the auth-json-server.

fix(core): allowGetBody shouldn't send empty body

---

packages/cli/src/generators/templates/authTests/digest.test.js
packages/cli/src/utils/auth-files-codegen.js
packages/core/integration-test/integration-test.js
packages/core/test/constants.js
packages/core/test/create-app.js
packages/core/test/create-request-client.js
packages/core/test/errors.js
packages/core/test/http-middleware.js
packages/core/test/logger.js
packages/core/test/request-client-internal.js
packages/core/test/tools/file-stasher.js
packages/core/test/userapp/index.js
packages/legacy-scripting-runner/test/constants.js
packages/legacy-scripting-runner/test/example-app/api-key-auth.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/example-app/oauth2.js
packages/legacy-scripting-runner/test/integration-test.js
packages/legacy-scripting-runner/test/zfactory.js

Replaces all `httpbin.org` with `httpbin.zapier-tooling.com`. Most of the changes are in tests, so there are no user or developer-facing changes. The only change that affects developers is the `digest-auth` project template.
The biggest difference between httpbin.org and httpbin.zapier-tooling.com is that the Zapier one uses arrays to hold values for headers and query params. So in the test code, we need to change a lot of `.should.eql(value)` to `.should.deepEqual([value])`.
While I was there, I refactored some of promise usages into async/await syntax.

refactor(cli,core,legacy-scripting-runner): use Zapier-hosted httpbin

---

packages/cli/src/smoke-tests/smoke-tests.js
packages/cli/src/tests/_helpers.js
packages/cli/src/tests/utils/build.js
packages/schema/docs/build/schema.md

Fixes yet another circular dependency in the CLI test code. I was releasing v10 and:
- core depended on schema v10
- schema v10 wasn't on npm registry
- broke cli tests (`build` command tests and smoke tests)
So we need to patch `zapier-platform-core`'s `package.json` to make sure it uses local `zapier-platform-schema`.

fix(cli): fix npm registry dependency in tests

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html
packages/cli/snippets/async-polling.js
packages/cli/snippets/custom-fields.js
packages/cli/snippets/dehydration.js
packages/cli/snippets/dynamic-dropdowns-five.js
packages/cli/snippets/manual-request.js
packages/cli/snippets/middleware.js
packages/cli/snippets/output-fields.js
packages/cli/snippets/process-env.js
packages/cli/snippets/put.js
packages/cli/snippets/session-auth.js
packages/cli/snippets/stash-file.js
packages/cli/snippets/xml.js

Add v10 notes everywhere in the docs, especially with `response.data` and `response.throwForStatus()`, so developers don't get confused if they're still on v9.

docs: add v10 notes

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

Use `new URL(url).toString()` to encode any unescaped characters before calling `z.request`. This would prevent node-fetch from throwing an error saying `Request path contains unescaped characters`.

fix(legacy-scripting-runner): encode URL path before sending a request

---

.gitignore
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js
packages/schema/docs/build/schema.md

`new URL(url)` correctly encoded non-english characters, but downcased everything. as a result, `{{process.env.THING}}` became `{{process.env.thing}}` and wasn't correctly resolved later.

fix(legacy-scripting-runner) env vars not being resolved correctly in urls

---

packages/cli/src/utils/convert.js

fixes #234, where an auth key like `X-API-KEY` wasn't handled correctly in the resulting JS.
We could probably refactor this conversion code to use the declarative code we did during the eng retreat, but that's probably fine for now.

fix(cli) properly handle invalid keys during VB conversion

---

docs/cli.html
docs/cli.md
example-apps/oauth2/test/authentication.test.js
packages/cli/docs/cli.html
packages/cli/docs/cli.md
packages/cli/src/generators/templates/authTests/oauth2.test.js
packages/cli/src/oclif/commands/init.js
packages/cli/src/oclif/oCommands.js
packages/cli/src/tests/utils/build.js
packages/legacy-scripting-runner/test/integration-test.js
packages/schema/docs/build/schema.md

We forgot to uncomment the `init` command in `oCommands.js`, which the doc build script uses to pull a list of commands. Also, the example usage was wrong. It should be `zapier init`, not `zapier yo`.
Also, https://auth-json-server.zapier-staging.com/oauth/refresh-token now returns `a_token` instead of `a_new_token` for the access token, which causes some tests to fail. This PR also fixes that.

docs(cli): fix missing `init` command in docs

---

packages/cli/src/utils/build.js

A developer on CLI v10 can still use Core v9.x for their app. This is especially true for converted apps. Apps on Core v9.x run on Node 10, so we need to make sure to include the deasync Node 10 binding file in the built zip.

fix(cli): include deasync Node 10 binding in the built zip

---

packages/legacy-scripting-runner/middleware-factory.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

Fixes [PDE-1561](https://zapierorg.atlassian.net/browse/PDE-1561).
A `KEY_post` method may access the response header like this:
```js
function KEY_post_poll(bundle) {
var name = bundle.response.headers['My-Name'];
// ...
}
```
However, in CLI/VB world, our HTTP client is `node-fetch` and it lowercases response headers for us, so the above header accessing will break. It needs to be changed to `bundle.response.headers['my-name']`.
This PR adds an `afterResponse` middleware to make header keys case-insensitive, so both `my-name` and `My-Name`, or even `mY-NaMe` are going to work.
Stole from @codebycaleb's commit https://github.com/zapier/zapier-platform/commit/f0575398887a980f57207b0cff8b4ace3284de6c.

fix(legacy-scripting-runner): make response headers case-insensitive

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html
packages/schema/docs/build/schema.md

We should not rely on the bundle.meta.zap object in a CLI App, so we should remove the reference in the documentation. Slack discussion https://zapier.slack.com/archives/CH0SN5V0V/p1596691855293400

docs(cli): remove legacy reference to bundle.meta.zap

---

packages/core/src/tools/wrap-hydrate.js
packages/core/test/hydration.js

Original commit message:
The maximum URL size in Node 10+ is 8KB. We're setting a much lower limit for hydration payloads (2KB). This commit bumps that limit to get it much closer to the true upper bound.
Why not go for the true max of 6144 bytes? We add some additional overhead when converting from 'hydrate|||...|||hydrate'. There's a domain, a signature, other request headers, etc. 6000 pre-base64 is a nice, round number to cut off at.
--- 
On testing this out, I came to the realization that long `hydrate|||...|||hydrate` strings don't necessarily correlate to long URLs. The only time hydration really concerns a URL is after the results of `z.dehydrateFile`, which has a pretty standard length as far as I can tell. So I'm not sure we actually have a hard limit on how large of a payload …

refactor(core): Increase max payload size for hydration

---

packages/cli/src/utils/build.js
packages/core/smoke-test/smoke-test.js
packages/schema/docs/build/schema.md

CLI 10.1.0 incorrectly requires `_zapier-build` script to defined. To reproduce:
```
$ zapier -v
zapier-platform-cli/10.1.0 darwin-x64 node-v12.16.3
$ zapier init myapp --template minimal
...
$ cd myapp
$ yarn
...
$ zapier build
✖ Running _zapier-build script
›   Error: npm ERR! missing script: _zapier-build
›
›   npm ERR! A complete log of this run can be found in:
›   npm ERR!     /Users/eliang/.npm/_logs/2020-09-01T03_28_19_771Z-debug.log
›
›
›   re-run this command with `--debug` for more info
```
This is because of a misuse of `_.get()`. The diff should be self-explanatory.
Found this bug because the smoke tests were [failing](https://travis-ci.com/github/zapier/zapier-platform/jobs/379667535#L268). I'm not sure why the tests didn't catch that in …

fix(cli): _zapier-build should be optional

---

packages/core/src/tools/create-logger.js
packages/core/test/logger.js
packages/schema/docs/build/schema.md

Fixes https://github.com/zapier/zapier/issues/30341.
We're overzealously censoring everything in `bundle.authData` and `process.env`. A common usage is putting a `BASE_API_URL` in `process.env`. When a developer does that, they're going to see this in the logs:
To make HTTP logs easier to access, we should disclose URL-like values. But when the URL may contain credentials (basic auth username/password or query parameters), we still want to censor. The newly-added test case reflects that.

fix(core): don't censor safe URLs in logs

---

packages/cli/LICENSE
packages/cli/package.json
packages/core/LICENSE
packages/core/package.json
packages/legacy-scripting-runner/LICENSE
packages/legacy-scripting-runner/package.json
packages/schema/LICENSE
packages/schema/docs/build/schema.md
packages/schema/package.json

I manually copied the root license file into individual subfolders (since `npm` doesn't follow symlinks 😞 ). We could add that step to the build process, but I don't anticipate these files changing often, so it wasn't worth it for now. 
The odd `package.json` syntax is from [the npm docs](https://docs.npmjs.com/files/package.json#license), where it says we should point to a license file via `"SEE LICENSE IN <filename>"`. 
For more context, see ([slack](https://zapier.slack.com/archives/C5Z9BP4U9/p1599606761202900?thread_ts=1598480207.066400&cid=C5Z9BP4U9)) and https://github.com/zapier/zapier/pull/43703

chore(cli,schema,core,legacy-scripting-runner): copy licenses and add them to package.json

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

We have recommended using the `$HOIST$` keyword when appropriate, but it hasn't been present in any documentation yet. Here's an attempt at succinctly describing the usage of the keyword. 🤞

docs(cli): document the `$HOIST$` property

---

packages/cli/package.json
packages/cli/scripts/docs.js

This started as a PR to reduce our usage of `lodash` for size reasons, but I don't think it's worth the time right now. 
In any case, we don't actually have to ship this file as part of the CLI, so I moved it!

chore(cli): move docs script

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

```
invite -> users:add
collaborate -> team:add
apps -> integrations
env -> env:set / get
```
Additionally, picked up a couple of tiny typos that were present in the surrounding area when I saw them.

docs(cli): update "outdated" command references in docs

---

packages/core/src/tools/create-app-tester.js

While trying to leverage the paging cursor in the new `bulkReads` actions, I noticed the system was claiming the tokens being passed up were null. Found this check and modified to accommodate for `bulkReads`
I looked into adding tests, but it doesn't seem this restriction is tested anywhere. Not sure where a good place would be to add one, or if we're cool w this point change.

feat(core): Add bulkReads as a qualified user of the cursor storage

---

packages/core/src/tools/create-app-tester.js
packages/schema/docs/build/schema.md

`z.generateCallbackUrl()` presently returns `undefined` when called via `AppTester`. This commit adds a placeholder value to be returned by `z.generateCallbackUrl()` - `'auth-json-server.zapier-staging.com/echo'`.

fix(core): Add callback_url fallback for testing

---

packages/cli/package.json
packages/cli/src/oclif/hooks/versionInfo.js
packages/cli/src/smoke-tests/smoke-tests.js
packages/cli/src/utils/misc.js

This is a minor detail that's bugged me for a while - when we converted to `oclif`, we lost the ability to have custom info when `zapier --version` was run (which is explicitly asked for when people file issues). This is [what we used to do](https://github.com/zapier/zapier-platform/blob/3cbaa2f10bb45f5c2f88a7afb229c13b394a1483/packages/cli/src/utils/misc.js#L147-L200).
This restores availability for some of that info, plus allows us to add more later.

fix(cli): improve logging for debugging info

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html
packages/schema/docs/build/schema.md

Deliver the change per JIRA ticket [PDE-1644](https://zapierorg.atlassian.net/browse/PDE-1644), a sub-task of the overall story in [PDE-1641](https://zapierorg.atlassian.net/browse/PDE-1641).

[PDE-1644] Face out of the link to Slack.

---

packages/core/index.d.ts
packages/schema/docs/build/schema.md

linter is on the fritz again :/

fix(core): Change typescript HTTPResponse types to use `any` instead of `object`

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

Added some information about Fallback sample

docs(cli): Add "fallback sample" info

---

example-apps/babel/src/authentication.js
example-apps/basic-auth/authentication.js
example-apps/custom-auth/authentication.js
example-apps/digest-auth/authentication.js
example-apps/oauth1-trello/authentication.js
example-apps/oauth2/authentication.js
example-apps/session-auth/authentication.js
packages/cli/src/utils/auth-files-codegen.js

docs(examples): fixing a documentation typo (PDE-1821)

---

packages/legacy-scripting-runner/bundle.js
packages/legacy-scripting-runner/test/bundle.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

`pre_oauthv2_refresh` can be called twice if the first attempt failed. We're already ensuring `bundle.request.data` is an object on the first attempt but NOT on the second attempt.
More context in [PDE-1816](https://zapierorg.atlassian.net/browse/PDE-1816).

PDE-1816 fix(legacy-scripting-runner): bundle.request.data should be an object on the second attempt of pre_oauthv2_refresh

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/package.json
scripts/bump.js

PDE-1816: Release legacy-scripting-runner 3.7.6

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

We believe that due to tasks no longer being saved for 90 days, a callback posting after 30 days has a risk of failing, so the documentation should state 30 days as the max.

[SUPPORTESC-101] docs(cli): Change 90-day limit for callbacks to 30-day

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html
packages/schema/docs/build/schema.md

This updates the README to reflect changes presented in https://github.com/zapier/zapier/pull/46039. We're now exposing the `subscribeData` in `perform` _and_ `performUnsubscribe`.  
Related [JIRA Ticket](https://zapierorg.atlassian.net/browse/AP-137)
Are there any other pieces of documentation that I missed and should be updated?

docs: update readme to reflect change presented in AP-137

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/package.json
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js
packages/schema/docs/build/schema.md

Fixes an issue where a `pre` method (including `KEY_pre_poll`, `KEY_pre_write`, `pre_subscribe`, etc.) encodes the URL and causes the URL to be double encoded. The test should demonstrate how to reproduce.

PDE-1915: fix(legacy-scripting-runner): shouldn't double encode when pre method also encodes the URL

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

This docs addition provides more guidance to developers about use contexts when they are working with code for loading dynamic fields.
Relates to: https://github.com/zapier/visual-builder/pull/165

[SUPPORTESC-109] docs(cli): Add details about when dynamic fields are loaded

---

packages/legacy-scripting-runner/exceptions.js
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

This handles the case where:
1) we get an error response (status code is 4xx or 5xx), and
2) the `KEY_post_(poll|write|search)` method also throws an error
Which one should we throw, the response error (1) or script error (2)?
WB chooses the error based on the script error type. If the script error is one of the Zapier-defined exception classes, throw the script error; throw the response error otherwise.
More details can be found in [PDE-1918](https://zapierorg.atlassian.net/browse/PDE-1918).

PDE-1918: fix(legacy-scripting-runner): better choose between ResponseError and script error

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/package.json

PDE-1918: Release legacy-scripting-runner 3.7.8

---

packages/cli/src/oclif/commands/versions.js
packages/schema/docs/build/schema.md

Fixes [PDE-1944](https://zapierorg.atlassian.net/browse/PDE-1944)

docs(cli): add warning if user counts are still being calculated

---

packages/legacy-scripting-runner/exceptions.js
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js

ErrorException errors have a name property of 'AppError' which failed the check in chooseBetterError. Now DEFINED_ERROR_NAMES will contain the proper ErrorException name property. Additionally, this updates chooseBetterError to always throw the scriptError if no responseError is present.

PDE-1948: fix(legacy-scripting-runner): Fix chooseBetterError for ErrorException errors

---

packages/core/src/constants.js

This key was being filtered out because it wasn't a part of the SAFE_LOG_KEYS array. Support needs this key for troubleshooting, so I've added it in.

PDE-1974: chore(core): Add trigger_subscription_id to SAFE_LOG_KEYS array

---

packages/core/src/http-middlewares/before/disable-ssl-cert-check.js
packages/core/test/create-request-client.js

1. Disable SSL certificate checks in your [advance settings](https://zapier.com/app/settings/advanced).
2. Create a CLI/VB app with a trigger that redirects a request from an `https` URL to `http`. You can use a URL like `https://httpbin.zapier-tooling.com/redirect-to?url=http://example.com` to do that.
Successfully redirected to the `http` URL.
Error: `Protocol "http:" not supported. Expected "https:"`

PDE-1966: fix(core): allow redirecting from https to http while disabling SSL checks

---

packages/cli/src/oclif/commands/users/links.js

Change the phrasing of what the link does to invite to "a specific integration".

[SUPPORTESC-115] fix(cli): Fix phrasing of what the specific version links do

---

packages/core/src/errors.js
packages/core/test/errors.js
packages/core/test/tools/file-stasher.js

`z.request({raw: true})`, usually used for file dehydration, is failing to raise a proper `ResponseError` when it gets an error response. This is because the `ResponseError` class assumes `response.content` is always available, which is not true. In the `prepareResponse` middleware, we make `reponse.content` [throw an error](https://github.com/zapier/zapier-platform/blob/4f4f9383d92a9c43a6308bc564b18e989f18fda9/packages/core/src/http-middlewares/after/prepare-response.js#L20-L24).
The fix is to be more defensive in `ResponseError`. When `response.content` throws an error, we simply keep `ResponseError.content` null.
---
fixes https://github.com/zapier/zapier-platform/pull/315

PDE-1982: fix(core): ResponseError shouldn't assume response.content is always present

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/package.json

PDE-1980: Release legacy-scripting-runner 3.7.9

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

The old version of these snippets would return an "undefined" result. This change makes copying and pasting more accessible.

SUPPORTESC-121: docs(cli): Make file stashing snippets copy-paste-ible

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

Fixes typos that I found when [copying](https://github.com/zapier/visual-builder/pull/172) the contents to the platform.zapier.com doc site.

PDE-1980: fix(docs): fix typos in README

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

Fixes OAuth2 scripting discrepancies:
- If `pre_oauthv2_token` or `pre_oauthv2_refresh` is defined, we should NOT retry to fetch or refresh the access token.
- We should not retry either if the error is not thrown by `response.throwForStatus()`. That is, retry only when it's a `ResponseError`.
- The OAuth payload for `pre_oauthv2_token` should be in `bundle.request.params`. Previously, we were setting `bundle.request.data` on the first attempt. And only if it fails, we retried it with `bundle.request.params`.

PDE-2012: fix(legacy-scripting-runner): pre_oauthv2_token and pre_oauthv2_refresh discrepancies

---

packages/cli/scaffold/test.template.js
packages/cli/src/oclif/commands/scaffold.js
packages/cli/src/smoke-tests/smoke-tests.js

Test files were still using a `mocha` setup instead of `jest`. Now newly-scaffolded tests will run correctly.
[PDE-1907](https://zapierorg.atlassian.net/browse/PDE-1907)

fix(cli): ensure test files can be run out of the box with jest

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/package.json

PDE-2012: Release legacy-scripting-runner 3.7.10

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

In `pre_oauthv2_token`, `bundle.auth_fields` should contain yet-to-save auth fields. `bundle.auth_fields` was empty because:
- yet-to-save auth fields are in `bundle.inputData` in the CLI world
- we were copying only from `bundle.authData`, not from `bundle.inputData`, to `bundle.auth_fields`

PDE-2012: fix(legacy-scripting-runner): yet-to-save auth fields should be in bundle.auth_fields

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/package.json

PDE-2012: Release legacy-scripting-runner 3.7.11

---

packages/schema/docs/build/schema.md
packages/schema/exported-schema.json
packages/schema/lib/schemas/AuthenticationOAuth2ConfigSchema.js

This change allows CLI developers using OAuth2 to specify a non standard parameter for us to scrape instead of code. Some Oauth flows, such as Amazon, respond from the authorizeUrl with a parameter other than code.  
[Amazon Docs](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-3-amazon-sends-you-the-authorization-information)
|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |
https://zapierorg.atlassian.net/browse/PDE-2002
All CLI integrations could only use OAuth2 if the …

PDE-2002: feat(schema): Add ability to specify "code" param to OAuth2 schema

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/bundle.js
packages/legacy-scripting-runner/test/bundle.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

In `pre_subscribe` and `post_subscribe`, `bundle.trigger_data` should contain the same values as `bundle.trigger_fields` does. `bundle.trigger_data` is considered deprecated but there are app still using it.

PDE-2079: fix(legacy-scripting-runner): add bundle.trigger_data to pre_subscribe

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/file.js
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

Fixes edge cases with optional file fields.
- When the action has an optional file field and it's empty, we should encode the request body in JSON as if the file field didn't exist (as opposed to doing `multipart/form-data` encoding).
- Only when the file field is set, we encode the request body in `multipart/form-data`.
Also, fixes another bug where boolean values crash `form-data`:
```javascript
const FormData = require('form-data');
const form = new FormData();
form.append('yes', true);
form.submit('https://httpbin.zapier-tooling.com/post', function (err, res) {
console.log(res.statusCode);
});
// ^^^ would crash with the following error:
// TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer.
// Received type boolean (true)
```
So …

PDE-2087: fix(legacy-scripting-runner): fix file field inconsistency

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/package.json

PDE-2087: Release legacy-scripting-runner 3.7.12

---

CHANGELOG.md
docs/cli.html
docs/cli.md
packages/cli/docs/cli.html
packages/cli/docs/cli.md
packages/cli/src/oclif/commands/test.js

Sort of addresses https://github.com/zapier/zapier-platform/issues/338- 
Rather than hard-code some test-runner-specific flags, we can just let users pass data through to whatever's in their `test` script.
Notes to include in eventual changelog to help migration and describe the breaking changes:
* In the command `zapier test -g asdf`, the `-g` flag will no longer get passed onto the test runner. It needs to be `zapier test -- -g asdf` instead
* Previously, we were passing a `timeout` value of `2000` (if you hadn't been specifying `-t|--timeout` explicitly in `zapier test`) to your test runner. If you want that behavior to continue, you need to add that flag manually after a `--`. Only relevant if you use `mocha` (`jest` has a different flag name). …

BREAKING CHANGE(cli): tweak test command to pass on extra args

---

.travis.yml
boilerplate/scripts/build.sh
docs/index.html
packages/cli/README.md
packages/cli/docs/index.html
packages/cli/src/constants.js
packages/cli/src/utils/build.js
packages/cli/src/version-store.js

I figured I'd do a dep update in a separate PR. 
Also, I _think_ we can take advantage of the travis [build matrix](https://docs.travis-ci.com/user/build-matrix/) feature to more cleanly declare our tests. On each of 12 and 14, run each of `test` and `smoke test`. I know you mentioned travis being slow;  i'm not sure this will help a lot, but it'll at least clean up that file.

BREAKING CHANGE(core) run apps using node 14

---

packages/core/index.d.ts

this might be a breaking change, depending on what objects developers have passed to `dehydrate` methods - wrong calls (with extra fields in `inputData`) will be marked so one can consider it a fix rather than a breaking change.
if extra `inputFields` fields should be tolerated a union with generic index type (i.e. `T & { [extra: string]: any }`) will describe the `inputData` more loosely.

fix(core): inputData for hydration function should be of type T as well (PDE-2198)

---

example-apps/typescript/tsconfig.json
packages/cli/src/generators/templates/typescript/tsconfig.json

as per https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping
node 12 is es2019 compatible

PDE-2205: build(core): typescript target es2019 for node 12

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/bundle.js
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/package.json
packages/legacy-scripting-runner/test/integration-test.js

In the CLI world, `bundle.authData` always holds the auth fields that are already saved to the Zapier database. When rendering `authorizeUrl`, auth fields aren't saved yet, which means `bundle.authData` either is empty or holds auth fields with default values.
These occasions:
- rendering `authorizeUrl`
- rendering access token URL when performing `getAccessToken`
- generating `bundle.auth_fields` for `pre_oauthv2_token` and `post_oauthv2_token`
... all happen before the auth fields are saved. So we need to make sure values in `bundle.inputData` take precedence over `bundle.authData`. For example, for an `authorizeUrl` with a value of `https://{{domain}}/example`, we should replace `{{domain}}` with `bundle.inputData.domain` instead of `bundle.authData.domain`.

PDE-2199: fix(legacy-scripting-runner): inputData should take precedence over authData when auth fields are not saved yet

---

packages/core/src/tools/create-file-stasher.js
packages/core/test/tools/file-stasher.js

This Pull Request fixes [this issue](https://github.com/zapier/zapier-platform/issues/169)
Previously, when await was used on a request that was passed to z.stashFile like so:
```
const x = await z.request(...);
return z.stashFile(x);
```
formData would throw the `source.on is not a function`. This PR fixes that issue. 
Jira: https://zapierorg.atlassian.net/browse/SUPPORTESC-148

SUPPORTESC-148 fix(core): stashFile no longer throws 'source.on' error when a request that uses await is passed in

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/package.json
packages/legacy-scripting-runner/test/integration-test.js

Suppose a legacy app uses "API Key in Header" auth and has this auth mapping:
```json
{
"X-Api-Key": "{{api_key}}"
}
```
Doing this in a `pre` method will cause two duplicate headers, `X-Api-Key` and `x-api-key`, being sent:
```javascript
function(bundle) {
bundle.request.headers = {
'x-api-key': bundle.auth_fields.api_key
};
}
```
Some web servers may not like it.

PDE-2333: Fix case-insensitive duplicate headers

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/middleware-factory.js
packages/legacy-scripting-runner/package.json
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

Turns out #364 only fixes part of the issue. This PR fixes another edge case that can lead to duplicate API Key headers.

PDE-2333: Fix duplicate API Key headers part 2

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/package.json
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js
packages/legacy-scripting-runner/zfactory.js

In a scripting method, pass an `auth` object to `z.request`:
```javascript
var response = z.request({
url: '...',
auth: {
bearer: 'my_token'
}
});
```
The [request](https://www.npmjs.com/package/request#http-authentication) library will send an `Authorization: Bearer my_token` header.
The `auth` argument is [set to null](https://github.com/zapier/zapier-platform/blob/b02ee5bee1452788ada9b71193bc31c7c668f272/packages/legacy-scripting-runner/zfactory.js#L16-L30) from the `z.request` call if it's not an array.

PDE-2352: fix(legacy-scripting-runner): auth can be an object for z.request

---

packages/cli/src/oclif/commands/env/set.js
packages/cli/src/oclif/commands/env/unset.js

Fixes [PDE-2356](https://zapierorg.atlassian.net/browse/PDE-2356). 
1. First, explicitly check that the version exists before we try to make an API call (the server error isn't super helpful here)
2. Also, `this.error` expects a string, so if we get an list of errors back, we should only send the first one. That's the `TypeError: first argument must be a string or instance of Error` in the jira ticket.

fix(cli): handle missing versions better in env command

---

packages/schema/lib/functional-constraints/uniqueInputFieldKeys.js
packages/schema/test/functional-constraints/uniqueInputFieldKeys.js

Fixes https://github.com/zapier/zapier-platform/issues/375 (and [PDE-2410](https://zapierorg.atlassian.net/browse/PDE-2410))

fix(schema): skip checking keys on fields without key properties

---

docs/index.html
packages/cli/README.md
packages/cli/docs/index.html
packages/cli/snippets/middleware.js

fixes https://github.com/zapier/zapier-platform/issues/382

docs(cli): return response in middleware

---

packages/cli/src/utils/auth-files-codegen.js

https://github.com/zapier/zapier/issues/50045

[PDE-2554] fix(cli): Remove string literal from boolean reference in session-auth example

---

packages/core/package.json
packages/core/src/constants.js
packages/core/src/tools/create-logger.js
packages/core/src/tools/data.js
packages/core/test/logger.js
packages/core/test/misc-tools.js
yarn.lock

Incorporates my hackathon project, the secret scrubber, into the platform!
It was mostly a project of moving and improving existing scrubbing code. Now, others can take advantage of it too!
[PDE-2555](https://zapierorg.atlassian.net/browse/PDE-2555)

feat(core): incorporate secret-scrubber into core

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

Fixes https://github.com/zapier/zapier/issues/50077.
Say there's an action of which key is `upload`. It has a file field `file` with the following `upload_pre_write` method defined:
```javascript
var Zap = {
upload_pre_write: function(bundle) {
bundle.request.files = {};
}
};
```
The `bundle.request.files = {}` line should make legacy-scripting-runner "cancel" encoding request body in `multipart/form-data` and go back to encode the body in `application/json`.

PDE-2556: fix(legacy-scripting-runner): don't make multipart body if `request.files` is empty

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/package.json

PDE-2556: chore(legacy-scripting-runner): release legacy-scripting-runner 3.7.17

---

.travis.yml
packages/core/src/create-command-handler.js
packages/core/src/tools/create-lambda-handler.js
packages/core/src/tools/schema-tools.js
packages/core/test/tools/schema-tools.js
packages/legacy-scripting-runner/test/integration-test.js

This is a 9.x backport merging into the `release-9.x` branch. I created this new branch `release-9.x` from tag `zapier-platform-cli@9.4.2` so we can release more `9.x` versions from that branch. Once this PR is approved, I'll merge and cut a release **9.5.0**.
This PR addresses two Jira tickets:
- [PDE-2564](https://zapierorg.atlassian.net/browse/PDE-2564): Add `async/await` support for Visual Builder (hackathon project)
- [PDE-2465](https://zapierorg.atlassian.net/browse/PDE-2465): Backport #387 to 9.x to make sure calling `z.request()` in the legacy script is logged
For [PDE-2564](https://zapierorg.atlassian.net/browse/PDE-2564), this patch allows developers to use the `await` operator in Visual Builder's Code Mode. For example, Visual Builder may generate this code for auth testing: …

PDE-2564: core(feat): allow using await in inline function source (9.x backport)

---

CHANGELOG.md
packages/core/src/create-command-handler.js
packages/core/src/tools/schema-tools.js
packages/core/test/tools/schema-tools.js

Same as https://github.com/zapier/zapier-platform/pull/390 but on the master branch.

PDE-2564: core(feat): allow using `await` in inline function source (11.x)

---

packages/cli/src/utils/convert.js

#390 and #396 will allow developers to use `await` in Visual Builder. However, we need to make sure when the Visual Builder app is converted by the `zapier convert` command, the functions are `async` prefixed. Otherwise, there could be `await` in regular functions, which is illegal in JavaScript.

PDE-2564: fix(cli): `convert` command should always generate async functions

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html
packages/cli/snippets/jest-adhoc-func.js
packages/core/index.d.ts
packages/core/src/tools/create-app-tester.js
packages/core/src/tools/resolve-method-path.js
packages/core/test/test-tools.js
packages/core/test/tools/resolve-method-path.js

Addresses https://github.com/zapier/zapier-platform/issues/16.
see also: [PDE-2539](https://zapierorg.atlassian.net/browse/PDE-2539)
1. With this PR cloned locally, run `yarn link` in the `core` directory
2. elsewhere, run `zapier init ad-hoc-test -t custom-auth`
3. run `cd ad-hoc-test && yarn && yarn link zapier-platform-core`
Now, `appTester` can be fed ad-hoc functions. Try the following test:
```js
/* globals describe, it, expect */
const zapier = require("zapier-platform-core");
const App = require("../index");
const appTester = zapier.createAppTester(App);
describe("custom auth", () => {
it("passes authentication and returns json", async () => {
const bundle = {
authData: {
apiKey: "secret",
},
};
const response = await appTester(
(z, bundle) =>
z.request({ url: …
```

feat(core): allow running adhoc functions in tests

---

packages/core/index.d.ts

See https://github.com/zapier/zapier/pull/50527 which will add `meta.isBulkRead` for platform >= 11.1.0.

feat(core): TN-168 Adds meta.isBulkRead TypeScript binding for platform 11.1.0

---

packages/core/src/tools/create-app-tester.js
packages/core/src/tools/should-paginate.js
packages/core/test/test-should-paginate.js

In order to make a CLI hook trigger compatible with Transfer, it needs to be able to set `canPaginate` for its `performList` method.  This PR updates the app tester to validate such a schema.
I wasn't sure whether `create-app-tester` is something third party devs might import, or if it's only used internally by us, but to be safe I refactored `shouldPaginate` into its own file rather than refactor `create-app-tester.js`'s module.exports.

feat(core): TN-169 Updates the app tester to support hook with canPaginate for performList

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html
packages/schema/docs/build/schema.md

Adds a note about how headers are (re)formatted in the bundle, so that devs no longer need to guess/test.
Relevant to #290 - we may improve this in the future, in which case this addition would need to be removed.

[SUPPORTESC-179] docs(cli): Add information about header format in bundle.rawRequest

---

packages/cli/src/utils/npm.js
packages/core/smoke-test/smoke-test.js
packages/schema/smoke-test/smoke-test.js

NPM registry seems to no longer provide a `content-length` header for `HEAD` requests. This broke some of our smoke tests where we send a `HEAD` request to NPM registry to get the package size.
Here's an example failed build on Travis: https://app.travis-ci.com/github/zapier/zapier-platform/builds/235320597
This PR fixes the issue by replacing the `HEAD` request with a `GET` request.

PDE-2636 fix(tests): failing smoke tests on package size

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/integration-test.js

When calling a scriptless polling trigger, if the response body is a string "null", legacy-scripting-runner should make it an empty array instead of throwing an error saying `JSON results array could not be located`.

PDE-2666 fix(legacy-scripting-runner): polling trigger should coerce a "null" response to an empty array

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/package.json

PDE-2666 chore(legacy-scripting-runner): release legacy-scripting-runner 3.8.0

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js
packages/legacy-scripting-runner/zfactory.js

In Web Builder scripting, developers could pass `json: true` to `z.request()`:
```js
var Zap = {
KEY_write: function(bundle) {
var data = z.JSON.parse(bundle.request.data);
data.hello = 'world';
var response = z.request({
method: 'POST',
url: 'https://httpbin.zapier-tooling.com/post',
json: true,
body: data  // <- an object
});
return response.content;  // <- an object
}
};
```
The returned result should be an object containing `{"json": {"hello": "world"}}`. This PR fixes legacy-scripting-runner to recreate this behavior.

PDE-2704 fix(legacy-scripting-runner): add support for `z.request({ json: true })`

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

```js
var Zap = {
KEY_pre_write: function(bundle) {
bundle.request.url = 'https://auth-json-server.zapier-staging.com/echo';
bundle.request.data = '';
// or bundle.request.data = null;
}
};
```
The request body should be an empty string.
The request body is JSON-encoded empty object, i.e., `{}`.

PDE-2751 fix(legacy-scripting-runner): Empty `request.data` should send an empty request body instead of an empty object

---

.travis.yml
packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/middleware-factory.js
packages/legacy-scripting-runner/package.json
packages/legacy-scripting-runner/test/integration-test.js

Session auth in headers with the following auth mapping:
```json
{
"x-api-key": "{{api_key}}",
"content-type": "application/json"
}
```
Then run an action with **no scripting**.
Only one `content-type: application/json` header should be sent.
Two duplicate `content-type: application/json` headers are sent.
Related to the previous fixes with API Key auth:
- https://github.com/zapier/zapier-platform/pull/364
- https://github.com/zapier/zapier-platform/pull/365

PDE-2737 fix(legacy-scripting-runner): duplicate headers with session auth

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

* Removed an outdated link to v2 documentation
* Clarify return type behavior for search
* Add note about the function of empty arrays for hook triggers

[SUPPORTESC-198] docs(cli): Update return types for current platform and add a few details

---

packages/core/src/tools/cleaner.js

Given an object with M keys and a bank with N keys, we call replacer M * N times. The actual replacer is pretty light-weight, except for its usage of Regex. With a bank size of ~4000 keys and a object size of ~500 keys, we can see 2,000,000 compilations of Regex. It can cause quite a slowdown!
This change will still result in N * M calls to replacer, but only N compilations of Regex.

SUPPORTESC-214 perf(core): Speed up cleaner.js

---

LICENSE
packages/cli/LICENSE
packages/core/LICENSE
packages/legacy-scripting-runner/LICENSE
packages/schema/LICENSE

Simple text update to increase clarity.
Duplicated into multiple files, but since it changes so infrequently, doesn't seem worthwhile to automate it (like we do with `docs`).
[PDE-2817](https://zapierorg.atlassian.net/browse/PDE-2817)

chore(cli, schema, core, legacy-scripting-runner): Update License files

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/package.json
packages/legacy-scripting-runner/test/integration-test.js

This is new bug caused by #435.
- Executing a polling trigger with _no_ script
- Polling URL (`legacy.triggers.{key}.operation.url`) has an inline querystring, such as `https://example.com?foo=bar`
- Auth mapping (`legacy.authentication.mapping`) is `{"api_key": "{{api_key}}"}`
- Auth placement (`legacy.authentication.placement`) is `querystring`
- `bundle.authData` is `{"api_key": "secret"}`
```json
{
"url": "https://example.com",
"method": "GET",
"params": {
"foo": "bar",
"api_key": "secret"
}
}
```
```json
{
"url": "https://example.com",
"method": "GET",
"params": {
"foo": "bar",
"api_key": ["", "secret"]
}
}
```

PDE-2859 fix(legacy-scripting-runner): fix empty auth params in `request.params`

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/integration-test.js

```js
var Zap = {
email_catch_hook: {
bundle.cleaned_request.file = z.dehydrateFile('https://httpbin.zapier-tooling.com/get', {});
return bundle.cleaned_request;
}
};
```
When hydrated, we should NOT see the auth headers or params in the request.
But if you do `z.dehydrateFile('https://httpbin.zapier-tooling.com/get')` (omitting the second argument for request options), we _should_ see the auth headers or params.
When hydrated, we see the auth headers or params in the request. Some server doesn't like it when the URL you're requesting for doesn't require auth but you give it auth info. For example, AWS S3 would give you HTTP 400 error saying `Unsupported Authorization Type`.

PDE-2872 fix(legacy-scripting-runner): `z.dehydrateFile(url, {})` should not send auth

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/package.json
packages/legacy-scripting-runner/test/integration-test.js

Fixes [PDE-2871](https://zapierorg.atlassian.net/browse/PDE-2871), where a partner's API depends on `redirect_uri` always being there (even for refresh)
I'm _pretty_ sure this'll fix it, but it's worth double checking the GL links in the jira ticket.

fix(legacy-scripting-runner): make sure redirect_uri is available for oauth refreshes

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

```js
var Zap = {
movie_pre_write: {
bundle.request.url = 'https://httpbin.zapier-tooling.com/post?foo=&bar=';
bundle.request.params.foo = undefined;
bundle.request.params.bar = null;
bundle.request.params.baz = '';
}
};
```
```js
{
"url": "https://httpbin.zapier-tooling.com/post",
"method": "POST",
"params": {
"foo": [""],
"bar": ["", "None"],  // 🤦‍♂️
"baz": [""]
}
}
```
```js
{
"url": "https://httpbin.zapier-tooling.com/post",
"method": "POST",
"params": {
"foo": ["", ""],
"bar": ["", ""],
"baz": [""]
}
}
```

PDE-2874 fix(legacy-scripting-runner): prune nulls and undefined's from query params

---

packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

Some converted apps possess actions which return an array, rather than an object, which causes the platform to raise an error `JSON results object could not be located.`
In these situations, the legacy scripting runner should return an object `{ "message": results[0] }`

PDE-2875 fix(legacy-scripting-runner): handle string array output from a scriptless create/action

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/package.json
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

```js
var Zap = {
movie_pre_write: function(bundle) {
bundle.request.url = 'https://auth-json-server.zapier-staging.com/echo';
bundle.request.data = {
foo: 'bar',
apple: 123
};
},
};
```
```js
{
"method": "POST",
"headers": {
// ...
"content-type": "application/json; charset=utf-8"
},
"textBody": "foo=bar&apple=123"
}
```
```js
{
"method": "POST",
"headers": {
// ...
"content-type": "application/json; charset=utf-8"
},
"textBody": "{\"foo\":\"bar\",\"apple\":123}"
}
```

PDE-2869 fix(legacy-scripting-runner): encode `request.data` in `form-urlencoded` for `pre` methods

---

packages/core/package.json
yarn.lock

node-fetch 2.6.0 doesn't encode URLs. For the following program:
```js
const fetch = require('node-fetch');
async function main() {
const response = await fetch('https://auth-json-server.zapier-staging.com/中文');
console.log(await response.text());
}
main();
```
node-fetch 2.6.0 gives you an error:
```
UnhandledPromiseRejectionWarning: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
```
Upgrading node-fetch to 2.6.6 fixes the problem.

PDE-2085 chore: bump node-fetch 2.6.0 -> 2.6.6 (9.x backport)

---

packages/cli/package.json
packages/core/package.json
yarn.lock

PDE-2085 chore: bump node-fetch to 2.6.6

---

packages/cli/package.json
packages/schema/package.json
yarn.lock

Bumps node-fetch for zapier-platform-cli and zapier-platform.schema. Forgot to do it in https://github.com/zapier/zapier-platform/pull/458.

PDE-2085 chore(cli, schema): bump node-fetch to 2.6.6 (9.x backport)

---

packages/core/package.json
packages/core/src/tools/create-file-stasher.js
packages/core/src/tools/fetch.js
packages/core/test/tools/fetch.js
yarn.lock

PDE-2826 fix(core): backpressure issue with node-fetch patch (9.x backport)

---

packages/core/src/tools/create-file-stasher.js
packages/core/src/tools/fetch.js
packages/core/test/tools/fetch.js

Using node-fetch 2.6.6 (Node.js 14), this program hangs on my laptop:
```js
const fs = require('fs');
const fetch = require('node-fetch');
async function main() {
// 36864 bytes = 16 KB
// If it's 36863, the bug won't happen
const downloadUrl = 'https://httpbin.org/stream-bytes/36864';
const downloadResponse = await fetch(downloadUrl);
const uploadUrl = 'https://httpbin.org/put';
const uploadOpts = {
method: 'PUT',
body: downloadResponse.body,
};
const uploadRequest = new fetch.Request(uploadUrl, uploadOpts);
const uploadPromise = fetch(uploadRequest);
const uploadResponse = await uploadPromise;
console.log(uploadResponse.status);
}
main();
```
When you pass a `fetch.Request` object to `fetch()`, `fetch()` [copies](https://github.com/node-fetch/node-fetch/blob/v2.6.6/src/index.js#L46) the …

PDE-2826 fix(core): backpressure issue with node-fetch patch

---

example-apps/files/creates/uploadFile_v10.js
example-apps/files/package.json
packages/cli/src/generators/index.js
packages/cli/src/generators/templates/files/creates/uploadFile_v10.js
packages/cli/src/generators/templates/files/test/creates.test.js

Fixes the flaky smoke test with the `files` example.
This [script](https://gist.github.com/eliangcs/eb8a93ff9a6ed09d777a0838423da0d4) proves that the original implementation of `makeDownloadStream()` in `uploadFile_v10.js` can miss the first chunk of bytes when downloading a file. I can't replicate the issue with a standalone Node.js program. But I found by pausing the file download stream, we can prevent the stream from being consumed too early.

PDE-2773 fix(cli): byte missing issue with `files` example

---

packages/cli/src/tests/utils/build.js
packages/core/src/tools/cleaner.js
packages/core/test/create-request-client.js

Given `bundle.inputData.foo` is non-existent, doing this will give you `value.replace is not a function` error:
```javascript
const perform = (z, bundle) => {
const response = await z.request({
url: 'https://example.com',
method: 'POST',
body: {
inputs: ['{{bundle.inputData.foo}}'],
}
});
return z.JSON.parse(response.content);
};
```
And this is the traceback:
```
Unhandled error: TypeError: value.replace is not a function
TypeError: value.replace is not a function
at handleEmpty (:censored:9:d1ba0cf2aa:/node_modules/zapier-platform-core/src/tools/cleaner.js:137:27)
at :censored:9:d1ba0cf2aa:/node_modules/zapier-platform-core/src/tools/cleaner.js:150:7
at Array.forEach (<anonymous>)
at normalizeEmptyRequestFields (:censored:9:d1ba0cf2aa:/node_modules/zapier-platform-core/src/tools/cleaner. …
```

PDE-2946 fix(core): fix `value.replace is not a function` when resolving missing curlies (9.x backport)

---

packages/core/src/tools/cleaner.js
packages/core/test/create-request-client.js

PDE-2946 fix(core): fix `value.replace is not a function` error when resolving missing curlies (11.x)

---

docs/cli.html
docs/cli.md
packages/cli/docs/cli.html
packages/cli/docs/cli.md
packages/cli/src/oclif/commands/test.js
packages/cli/src/tests/utils/package-manager.js
packages/cli/src/utils/package-manager.js

add `pnpm-lock.yaml` as recognized file to decide which package manager to run.
to accomplish this cleanly and future proof, i added a util-module for package managers, their lockfiles and their double-hyphen-needed-ness.
fixes #470

feat(cli) add support for pnpm package manager in test command (PDE-3000)

---

packages/core/ARCHITECTURE.md
packages/core/src/tools/create-legacy-scripting-runner.js
packages/legacy-scripting-runner/test/integration-test.js

Handle a rare case where `legacy.scriptingSource` is an empty string on a legacy app, so we don't initialize LSR. Then, `z.legacyScripting.run(...)` fails w/ `Cannot read property 'run' of undefined`.

fix(core): handle case where scriptingSource is an empty string

---

packages/core/src/tools/create-legacy-scripting-runner.js
packages/legacy-scripting-runner/test/integration-test.js

fix(legacy-scripting-runner): backport #475; handle empty scripting string

---

packages/cli/src/smoke-tests/smoke-tests.js
packages/core/src/constants.js
packages/core/src/tools/create-http-patch.js
packages/core/src/tools/create-lambda-handler.js
packages/core/src/tools/create-logger.js
packages/core/test/logger.js
packages/core/test/tools/mocky.js

Improves `z.console.log` and HTTP logging performance. In this PR, we stream many logs in a single request to the `/input` endpoint on the log server. This reduces the overhead where the original `/input` endpoint only took one log in a request.
I used the following trigger code for benchmark:
```js
const perform = async (z, bundle) => {
const response = await z.request('https://httpbin.zapier-tooling.com/get');
const requestId = response.data.headers['X-Request-Id'][0];
for (let i = 0; i < 200; i++) {
z.console.log(`hello ${i}`);
}
return [{ id: requestId }];
};
```
The above example code produces one HTTP log and 200 console logs. The old way (one log, one request) takes ~6.6 seconds to invoke the trigger. The new way (stream many logs in a request) takes ~3.5 seconds. I was expecting a …

PDE-2650 perf(core): improve logging performance

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

Add some additional context and links around OAuth2 refresh options, and some other auth cleanup for consistency/clarity.

[SUPPORTESC-297] docs(cli): Clarification on OAuth2 refresh details

---

docs/cli.html
docs/cli.md
packages/cli/docs/cli.html
packages/cli/docs/cli.md
packages/cli/src/oclif/commands/migrate.js
packages/cli/src/oclif/commands/promote.js

Internally points the CLI `promote` and `migrate` command to use the new [migration endpoint](https://github.com/zapier/zapier/blob/8379df093af726b2318083282889cd73eda4c81c/web/backend/zapier/app_platform/developer_cli/api/urls.py). 
These commands currently point to an endpoint that calls out to the new migration endpoint so this is work to remove that indirection.

PDE-2981: feature(cli) - Update "promote" and "migrate" to use new endpoint

---

packages/cli/package.json
packages/core/package.json
yarn.lock

node-fetch 2.6.7 has a security fix we'd like to include. See [Slack](https://zapier.slack.com/archives/C5Z9BP4U9/p1645459595701089) for more detail.

PDE-3045 chore(all): bump node-fetch to 2.6.7

---

packages/cli/package.json
packages/core/package.json
packages/schema/package.json
yarn.lock

PDE-3045 chore(all): bump node-fetch to 2.6.7 (for 9.x)

---

packages/core/src/tools/create-http-patch.js
packages/core/test/tools/http-patch.js

Fixes https://github.com/zapier/zapier/issues/53430.
The bug was introduced by #483. Affected core versions are 11.3.0 and 9.7.0. The root cause is the `httpPatch()` function was reusing the `logger` instance from the previous Lambda invocation. But since we [destroy](https://github.com/zapier/zapier-platform/blob/4d84c23e2965078c5dbe228188abd6a0ab0cff00/packages/core/src/tools/create-lambda-handler.js#L161) the logger at the end of a Lambda call, the logger wouldn't be valid for the subsequent call. This causes the subsequent call to wait for the invalid logger to respond and time out.
The symptoms of this bug:
- Long Lambda execution time, usually > 60 seconds
- Actions being invoked multiple times, because Zapier retries when it doesn't get a response from Lambda

PDE-3038 fix(core): dangling logger causes Lambda to hang

---

packages/cli/src/smoke-tests/smoke-tests.js
packages/core/src/tools/create-http-patch.js
packages/core/test/tools/http-patch.js

PDE-3038 fix(core): dangling logger causes Lambda to hang (9.x)

---

packages/core/src/http-middlewares/before/add-query-params.js
packages/core/test/http-middleware.js
packages/schema/docs/build/schema.md
packages/schema/exported-schema.json
packages/schema/lib/schemas/RequestSchema.js

Proof of concept to enable apps (especially legacy apps) to skip encoding certain params. 
Once thing I noticed (but didn't have time to dig into) was that if the url already includes params, we pull them out before the request object reaches `addQueryParams`:
```js
z.request('https://httpbin.org/get?in_url=asdf$$asdf')
// in `addQueryParams`
console.log(req)
{
method: 'GET',
params: { in_url: 'asdf$$asdf' },
url: 'https://httpbin.org/get',
// ...
}
// in request-client.js, directly before the call to `fetch(url, options)`
console.log('calling', url)
// calling https://httpbin.org/get?in_url=asdf%24%24asdf
```
But, as written, this will at least partially unblock us

feat(core,schema): enable skipping encoding specific characters from query params

---

packages/legacy-scripting-runner/file.js
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/package.json

Fixes two bugs with file uploading.
1. The `Content-Type` header should be set to `multipart/form-data` when uploading a file. We were using [form-data](https://www.npmjs.com/package/form-data) to generate the request body, but we should also use `form.getHeaders()` to generate a header like `Content-Type: multipart/form-data; boundary=----12345678`.
2. Hanging issue. We were using the [request](https://www.npmjs.com/package/request) package for 1) `z.request` in the legacy script and 2) downloading files. I found when there's a **sync** `z.request` call in the legacy script, the `request` call to download a file can hang the entire process. I'm not sure why but I guess it's related to [deasync](https://www.npmjs.com/package/deasync). This PR fixes the issue by replacing `request` with …

PDE-3006 fix(legacy-scripting-runner): fix issues with file uploading

---

boilerplate/scripts/build.sh

Allows to build boilerplate with one of these combinations of source:
| core  | legacy-scripting-runner | example command      |
|-------|-------------------------|----------------------|
| local | local                   | `build.sh`             |
| npm   | local                   | `build.sh 9.7.1`       |
| local | npm                     | `build.sh '' 3.8.5`    |
| npm   | npm                     | `build.sh 9.7.1 3.8.5` |

chore: allow to build boilerplate from local or npm

---

packages/core/src/http-middlewares/before/add-query-params.js
packages/core/test/http-middleware.js
packages/schema/docs/build/schema.md
packages/schema/exported-schema.json
packages/schema/lib/schemas/RequestSchema.js

feat(core,schema): enable skipping encoding specific chars from query params (9.x)

---

packages/legacy-scripting-runner/index.js

PR #497 and #499 added a `skipEncodingChars` option to `z.request()` and `RequestSchema`. We still need legacy-scripting-runner to utilize this option. If the app definition has a truthy `legacy.skipEncodingChars`, we should let legacy-scripting-runner pass it to `z.request()`.

feat(legacy-scripting-runner): pass `legacy.skipEncodingChars` to `z.request()`

---

boilerplate/scripts/build.sh

chore: allow to build boilerplate from local or npm (9.x)

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/package.json

PDE-3006 chore: release legacy-scripting-runner 3.8.6

---

.gitignore
CONTRIBUTING.md
README.md
packages/legacy-scripting-runner/CHANGELOG.md

Adds `CONTRIBUTING.md` and links to the internal release guide.

PDE-3048 docs: `CONTRIBUTING.md` and release guide

---

CONTRIBUTING.md
README.md

PDE-3048 docs: fix and add links

---

CONTRIBUTING.md
README.md
packages/core/test/create-request-client.js

Fixes a link in `CONTRIBUTING.md` and few tweaks in the docs.
I also had to replace `zapier-mockbin.herokuapp.com` occurrences with `httpbin.zapier-tooling.com` in some tests because those are no longer available.

docs(misc): fix link in `CONTRIBUTING.md`

---

packages/core/integration-test/integration-test.js
packages/core/src/tools/create-logger.js
packages/core/test/tools/mocky.js
packages/core/test/userapp/index.js

Related to #509, #490, and https://github.com/zapier/zapier/issues/53430, this addresses another scenario that causes the Lambda handler to hang/freeze.
Suppose a converted app has this (bad) legacy script:
```js
var Zap = {
bad_post_write: function(bundle, callback) {
z.request({ ... }, function(err, response) {
if (err) {
callback(err);
} else {
callback(null, z.JSON.parse(response.content));
}
});
callback(null, { message: 'ok' }); // double callback?!
}
};
```
Notice how the `post_write` function returns immediately by calling `callback(null, { message: 'ok' })` while makes an outbound `z.request()` and calls `callback` asynchronously.
When legacy-scripting-runner [promisifies](https://github.com/zapier/zapier-platform/blob/1632992ad4867b6cce1e8abb8fe60a866ba19fbc/packages/legacy-scrip …

fix(core): fix another scenario that causes hanging (11.x)

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html
packages/cli/snippets/middleware.js

Documentation for #512. The app-wide `skipThrowForStatus` is intentionally not documented because I don't anticipate CLI devs using that - they can do it in middleware if they'd like. 
Did some other cleaning while I was in there.

docs(core): document changes to autoRefresh

---

CHANGELOG.md
docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html
packages/core/src/execute.js
packages/core/test/create-app.js
packages/schema/docs/build/schema.md
packages/schema/exported-schema.json
packages/schema/lib/schemas/AppFlagsSchema.js

In `9.x`, shorthand requests (using objects instead of JS functions) _always_ threw for bad responses. We want to maintain that behavior in the 12.x release line. But, the global `skipThrowForStatus` changed the defaults for all requests, not just shorthand. So, this adds an explicit `skipThrowForStatus: false` default to shorthand requests. Native devs can still have specified `skip: true` for shorthand requests. This keeps the default behavior for 9.x shorthand requests even when we set the global flag on all godzilla apps 😵‍💫😵‍💫😵‍💫
Here's a table I made to help myself reason about the change:
> Behavior of a failing shorthand request when migrated between core versions (9 and 12 should match)
|global flag (on 12) | req flag | 9.x   | 10-11.x | 12.x  |
| ----------- | -------- | ----- | …

fix(core): tweak global `skipThrowForStatus` flag to ignore shorthand requests

---

packages/core/src/tools/cleaner.js
packages/core/test/create-request-client.js
packages/core/test/misc-tools.js

Fixes bug introduced in core version `11.1.1` where a quirk with regex objects wouldn't replace multiple curly strings in a row

fix(core): properly replace curlies that match multiple times in a row

---

packages/core/src/http-middlewares/after/log-response.js
packages/core/src/tools/create-app-request-client.js
packages/core/src/tools/create-logger.js
packages/core/test/logger.js
packages/legacy-scripting-runner/index.js

We've noticed a couple of edge cases where `access_tokens` sometimes aren't censored correctly in logs. Most of our censoring works by looking for explicit data that should be removed. But, during an auth refresh, we get a token back we've never seen before. So, we have to make sure to (at least attempt to) parse the response, search it for secrets, and censor those for logging.

fix(core): ensure string content is parsed pre-logging in case it contains secrets

---

packages/core/src/tools/create-logger.js
packages/core/test/logger.js
yarn.lock

Follow up to https://github.com/zapier/zapier-platform/pull/525 that covers similar behavior in the querystring.
---
Didn't catch it before because I passed the url `example.com?api_key=secret`, but prep request separates them, so we have to search `request_params` explicitly too.
Underscores the importance of our unit tests matching what actually gets called at runtime

fix(core): censor novel secrets in querystring

---

packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

This PR updates the Getting Started section of the CLI docs here: https://github.com/zapier/zapier-platform/blob/master/packages/cli/README.md#quick-setup-guide
At the moment, it's not clear on how you would login to Zapier through the CLI platform if your Zapier account was created using SSO. 
The terminal will give you steps on how to login via SSO:
However, reviewing Zendesk, I did find a handful of tickets where developers wrote in having issues searching "CLI SSO". This is one example: https://zapier.zendesk.com/agent/tickets/62778
And this more recent one: https://zapier.zendesk.com/agent/tickets/587189
I worked with Sydney on the paid support team to get this Look: https://zapier.looker.com/looks/5957
And found that ~58k developers use SSO.
I think that by bringing the SSO …

PDE-3149 Added SSO sign on instructions

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

Part of _Improve Dev Platform Docs_ for HackWeek 2022 Q1
As the example-apps folder is primarily used for older CLI versions now, we should update the links to point users towards using `zapier init` to build new projects as the first suggestion, with links to example-apps only as reference.

[PDE-3149] Update example-apps links to recommend `zapier init`

---

docs/cli.html
docs/cli.md
packages/cli/docs/cli.html
packages/cli/docs/cli.md
packages/cli/src/oclif/commands/team/get.js

JIRA: https://zapierorg.atlassian.net/browse/PDE-3152
Removes `subscribers` from `team:get` command
Fetches `limited collaborators` for `team:get` command.

PDE-3152 feat(cli) - Update `team:get` CLI command to fetch Collaborator.

---

docs/cli.html
docs/cli.md
packages/cli/docs/cli.html
packages/cli/docs/cli.md
packages/cli/src/oclif/commands/team/add.js

Fixes a grammar error (`has -> have`) on `team:add` help text.
Relates to https://github.com/zapier/zapier-platform/pull/539.

PDE-3153 cli(fix): fix grammar on `team:add`

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/package.json

Makes a `logResponse` import backward compatible with core 12.0.2 and 12.0.3.

PDE-3210 fix(legacy-scripting-runner): fix `logResponse` import

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/package.json
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

The legacy scripting [docs](https://platform.zapier.com/legacy/scripting) say `StopRequestException` is to silently cancel the request in a `pre_` method:
> Any pre_XXX call can be interrupted silently with StopRequestException. This will prevent the request from being made and will never cause a user’s Zap to be turned off.
Namely, if a `pre_` method throws a `StopRequestException`, Zapier should cancel the subsequent request sent to the partner and return an empty result.
Current behavior: `StopRequestException` is [transformed](https://github.com/zapier/zapier-platform/blob/69097765d3f6a13a8aa5c755a9824f170b0ccc52/packages/legacy-scripting-runner/exceptions.js#L54) to `StopRequestError` and is thrown as an uncaught error.
New behavior: Catch `StopRequestError` and return an empty array …

fix(legacy-scripting-runner): StopRequestException should be caught instead of thrown

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/package.json
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js

Continues the work of #558, this PR adds support for `StopRequestException` to all the methods, including `KEY_catch_hook`, `KEY_poll`, `KEY_write`, and `KEY_search`.

fix(legacy-scripting-runner): support `StopRequestException` in `KEY_catch_hook`, `KEY_poll`, `KEY_write`, `KEY_search`

---

packages/core/package.json
packages/core/src/tools/create-logger.js
packages/core/test/logger.js
packages/core/test/tools/mocky.js
yarn.lock

Fixes the issue where a Lambda invocation can take ~1 minute before a `socket hang up` error with the log server shows up.
You can find the steps to reproduce the error on [Slack](https://zapier.slack.com/archives/C5Z9BP4U9/p1657183594848969?thread_ts=1656322076.695299&cid=C5Z9BP4U9).
I’m not sure under what situations the log server would stop responding to an open connection on production. (Maybe the log server sometimes crashes?) But we should at least make the core more resilient and not affected by a hanging connection.
The idea is to limit the wait time for the log server to respond. We use node-fetch to make requests to the log server. And to abort a node-fetch request, we can use AbortController. See node-fetch's [README](https://github.com/node-fetch/node-fetch/tree/v2.6.7#request …

PDE-3251 fix(core): abort logger connection at the end of invocation

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/package.json
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js
packages/legacy-scripting-runner/zfactory.js

Fixes a regression caused by #509, where calling `z.request` in the legacy script does not (but should) produce an HTTP log.
For an HTTP request to be logged, it must call the patched [`http(s).request`](https://github.com/zapier/zapier-platform/blob/b580d5f781d4b6e1aeff49e906bb9f36f6872589/packages/core/src/tools/create-http-patch.js#L21) function. The patch is done [at the Lambda handler initialization time](https://github.com/zapier/zapier-platform/blob/b580d5f781d4b6e1aeff49e906bb9f36f6872589/packages/core/src/tools/create-lambda-handler.js#L202-L204).
But since #509 adopted [synckit](https://github.com/rx-ts/synckit) to implement the [sync version of `z.request`](https://platform.zapier.com/legacy/scripting#making-outbound-requests-zrequest) in the legacy script, the HTTP request for …

PDE-3318 fix(legacy-scripting-runner): `z.request` in legacy script isn't logged

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

I updated the ThrottledError example to call ThrottledError on z.errors. The current example does not use z.errors (`throw new ThrottledError()`).
ThrottledError is listed under z.errors in [the docs](https://github.com/zapier/zapier-platform/blob/master/packages/cli/README.md#zerrors), so this change makes this example consistent with the usage of other errors.
In my own testing, ThrottledError only gets thrown when z.errors is used.

[SUPPORTENG-406] Correcting ThrottledError example to include z.errors

---

packages/cli/src/utils/build.js

build(cli):  Log warnings at build time during validation

[PDE-3393] Log warnings at build time during validation

---

docs/cli.html
docs/cli.md
packages/cli/docs/cli.html
packages/cli/docs/cli.md
packages/cli/src/oclif/commands/promote.js

This flag suppresses prompts asking to confirm a corresponding changelog entry when running zapier promote. This is primarily for CI purposes and will still show warnings/info related to the changelog during zapier promote runs. I utilized oclif's [built-in boolean flag type](https://oclif.io/docs/flags) for this flag.
Usage: `zapier promote 1.0.0 --skip-changelog`

[PDE-3262] Add skip-changelog flag to zapier promote CLI command

---

CONTRIBUTING.md

PDE-3458 docs: document development workflow

---

packages/schema/docs/build/schema.md
packages/schema/exported-schema.json
packages/schema/lib/schemas/FieldSchema.js

I added some additional language to how Zapier processes `file` types in fields. It looks like our [user help docs](https://zapier.com/help/create/basics/different-field-types-in-zaps#step-4) provide some more additional details than our developer docs. So this will bring the developer docs in line with what we have that is public facing.
Additional information on how we process strings and that we make a GET request when we detect a URL.

[SUPPORTENG-385] Clarifying how fields accept file types

---

packages/core/package.json
yarn.lock

secret-scrubber saw some great memory and speed improvements from 1.0.3 to 1.0.7 (to the point that 1.0.3 is problematic for some apps).

SUPPORTENG-439 chore(core): Update secret-scrubber dependency requirement

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

The original goal of this work was to add information about the Copy field type (which we don't touch on in the current version). 
However, there wasn't much detail on field types in the CLI README at all. The schema had some information, but adding more details would probably make it unwieldy, so I thought it might be most helpful to update the README with a longer table about field types.
As the topic of type coercion in fields can be complex, I elected not to get into it too much, only covering some extreme basics.

[SUPPORTENG-379] docs(cli): Provide field type details under Input Fields in README

---

docs/index.html
packages/cli/README-source.md
packages/cli/docs/index.html

#592 only fixed the auto generated README.md. This PR copies the fix to README-source.md.

PDE-2828 docs: fix typo in README-source.md

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

We had some inconsistent information on types of logs and what's logged automatically; this PR removes the inconsistency and does some other light cleanup.

[SUPPORTENG-520] docs(cli): Update logging info

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

Changed every `zapier init [your app name] --custom-auth` (doesn't work) to `zapier init [your app name] --template custom-auth` (works)
See example below:

PDE-3635 docs (cli): Fix custom-auth template command

---

example-apps/typescript/package.json

The `should list only required file` test is [failing](https://github.com/zapier/zapier-platform/actions/runs/3676205062/jobs/6216561636#step:5:152):
```
76 passing (20s)
2 pending
1 failing
1) build (runs slowly)
"before all" hook for "should list only required files":
Error: npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1670851568773-0.5350270081264845/node but npm is using /opt/hostedtoolcache/node/12.22.12/x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1670851568773-0.5350270081264845/node but npm is using /opt/hostedtoolcache/node/12.22.12/x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the …
```

PDE-3685 chore(cli): upgrade typescript to fix a test

---

packages/schema/docs/build/schema.md
packages/schema/exported-schema.json
packages/schema/lib/functional-constraints/searchOrCreateKeys.js
packages/schema/lib/schemas/SearchOrCreateSchema.js
packages/schema/test/functional-constraints/searchOrCreateKeys.js

**EXPERIMENTAL: This feature is still in internal testing and is subject to change. Don't use it yet unless you're a Zapier employee.**
Before this PR, `searchUniqueInputToOutputConstraint` only allows string-to-string mapping. Now with this change, it can be nested to support dynamic fields. For example:
```js
const App = {
creates: {
add_row: { /* ... */ },
update_row: { /* ... */ },
},
searches: {
find_row: {
// ...
operation: {
inputFields: [
{ key: 'lookup_key' },
{ key: 'lookup_value' },
// ...
getCustomFields,  // a function to get custom fields
]
}
},
},
searchOrCreates: {
find_row: {
key: 'find_row',
display: {
label: 'Find, Create, or Update Row',
description: 'Finds, creates, or updates a row.',
},
search: 'find_row',
create: 'add_row',
update: 'update_row', …
```

PDE-3680 feat(schema): dynamic field support for upsert

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

GitHub's [light-dark color mode image](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to) seems to stop working. Let's just use an opaque SVG logo so it looks good on both light and dark modes.
Before (broken image):
After:

PDE-3266: Fix logo in docs

---

docs/cli.html
docs/cli.md
packages/cli/docs/cli.html
packages/cli/docs/cli.md
packages/cli/src/oclif/commands/convert.js

Spotted by @standielpls over at https://github.com/zapier/visual-builder/pull/401#discussion_r1087123753

docs(cli): Fix 'integraiton' typo in CLI docs

---

packages/cli/package.json
packages/cli/src/oclif/hooks/getAppRegistrationFieldChoices.js

This PR introduces a new hook `getAppRegistrationFieldChoices` that triggers during oclif's `init` hook (see [docs](https://oclif.io/docs/hooks)). The goal of this hook is to get enum field choices from `/api/platform/cli/apps/fields-choices` and provide them to `RegisterCommand` for use with forthcoming flags/prompts. It should not run on other commands.
This PR has no noticeable effect on current functionality.

PDE-3731 feat(cli): Add getAppRegistrationFieldChoices hook

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

The question of how to correctly return line items comes up periodically, to the point where we maintain an internal reference. This addition will allow developers curious about how to return line items to better self-serve.

[SUPPORTENG-394] docs(cli): Add information about how to return line items

---

packages/schema/docs/build/schema.md
packages/schema/examples/definition.json
packages/schema/exported-schema.json
packages/schema/lib/schemas/AuthenticationOAuth2ConfigSchema.js

Adds a new option to the OAuth2Config: `enablePkce`. 
This option will be read by the Zapier Platform backend to use PKCE for the authorization/access token exchange request flow. If this option is not provided, it will default to use the existing OAuth2 flow.

PDE-3242 - feat(schema) Add enablePkce to OAuth2Config

---

packages/cli/src/oclif/commands/register.js
packages/cli/src/tests/fixtures/createApp.js
packages/cli/src/tests/register.test.js
packages/cli/src/tests/utils/api.js
packages/cli/src/tests/utils/check-missing-app-info.js
packages/cli/src/utils/api.js
packages/cli/src/utils/check-missing-app-info.js

Currently, app meta fields/settings are only editable for private apps in the visual builder. Now that the CLI allows users to update these settings via CLI, we need to ensure that they can only update these settings for **private** apps.
[Jira story](https://zapierorg.atlassian.net/browse/PDE-3822)

PDE-3822 feat(cli): Only require fields for private integrations via CLI

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html
packages/cli/snippets/oauth2-pkce.js

Updates the Authentication to include a section on PKCE for OAuth2.

feat(docs) - Add documentation for PKCE OAuth2

---

packages/cli/src/tests/utils/check-missing-app-info.js
packages/cli/src/utils/check-missing-app-info.js

Since the BE field names that the API is expecting do not match the names of the flags we're using in the CLI, we need to make sure we're using the proper name in the proper context. This commit ensures that we're using proper names in the CLI error message when check-missing-app-info fails.

PDE-3664 feat(cli): Use uniform field names in check-missing-app-info util

---

CHANGELOG.md

* Sort changes by change type (instead of listing them sequentially)
* Remove Jira ticket numbers
* Remove PR change type hints
* Add "misc" section

PDE-3850 chore(cli, schema, core): Add more information about breaking changes to CHANGELOG.md

---

packages/cli/src/tests/utils/convert.js
packages/cli/src/utils/convert.js

In `packages/cli/src/utils/convert.js` for `zapier convert` the function `getAuthFieldKeys` does not check if the default keys already exist in the user-defined `authentication.fields`, and therefor generates duplicates in e.g. `.env`.
This PR fixes that and updates a test against regressions.

fix(cli): Fix convert duplicating auth fields

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

Modify copy to make platform behavior and implementation steps clearer: https://zapierorg.atlassian.net/browse/SUPPORTENG-905

[SUPPORTENG-905] Update "OAuth2 with PKCE" section

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

Modify copy to more clearly explain schema property relevance and usage for [output fields](https://github.com/zapier/zapier-platform/blob/main/packages/cli/README.md#output-fields): https://zapierorg.atlassian.net/browse/SUPPORTENG-907

[SUPPORTENG-907] Update "Output Fields" section

---

packages/schema/docs/build/schema.md
packages/schema/exported-schema.json
packages/schema/lib/schemas/BasicDisplaySchema.js
packages/schema/lib/schemas/SearchOrCreateSchema.js
packages/schema/lib/schemas/SearchOrCreatesSchema.js

Following the deprecation of this field https://github.com/zapier/zapier-platform/pull/644, this PR removes the `important` field from the `BasicDisplaySchema`

PDE-4011 - BREAKING CHANGE(schema) - Remove the important field

---

packages/cli/package.json
packages/cli/src/tests/utils/convert.js
packages/cli/src/utils/convert.js
yarn.lock

`IP-127` [Zapier Convert: Convert auth config source to functions](https://zapierorg.atlassian.net/browse/IP-127)
Inline functions under auth config objects are not converted to functions by `zapier convert`, while the test function is:
```js
const testAuth = async (z, bundle) => {
z.request({
url: "https://api.wistia.com/v1/account.json",
method: "GET",
headers: {
Authorization: "Bearer {{bundle.authData.access_token}}",
},
body: {},
}).then((response) => response.data);
};
module.exports = {
type: 'oauth2',
test: testAuth,
fields: [],
oauth2Config: {
getAccessToken: {
source:
"const options = {\n  url: 'https://api.wistia.com/oauth/token',\n  method: 'POST',\n  headers: {\n    'content-type': 'application/x-www-form-urlencoded',\n    accept: 'application/json',\n  },\n  body: {\n …
```

fix(core): Convert authentication config source functions to actual functions

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

This PR updates a few broken links to match them with the equivalents already in the platform's CLI docs (https://platform.zapier.com/cli_docs/docs).
It also includes a new note, which was already in `README-source.md` but wasn't pushed to other files in someone else's earlier commit.
Note, I had some trouble with the pre-commit hook, so I ran `yarn docs` and then staged/committed individual files. Please let me know if anything here looks incorrect and I'll fix re-submit.

[SUPPORTENG-916] Updating a few links to match platform docs

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

When following the quick setup guide, the lack of mention of environment variables could result in user confusion. If a required client id doesn't generate, the error we see, will be the API error when the authorizeUrl is wrong, so might not be clear that you need to set a client_id and client_secret to a user that has pushed a barebones CLI app. 
Also some outdated hyperlink updates.

SUPPORTENG-919_hyperlinks_update

---

packages/cli/README.md

Move up the explanation about templates to where user encounters them.

docs(cli): Move up template explanation in README

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

- Port back the doc change #682 from README.md to README-source.md.
- Update the links to the docs of old versions.
- Fix a sentence so it's more natural-sounding using ChatGPT.

PDE-4193 doc(cli): doc rebuild and minor updates

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

as suggested here https://zapier.slack.com/archives/C04P5J5R8E4/p1689900123007759 
also added detail for callback testing, per https://zapier.slack.com/archives/C5Z9BP4U9/p1691168493239769?thread_ts=1691167523.978609&cid=C5Z9BP4U9

SUPPORTENG-929_Adding detail on encoding default

---

packages/cli/src/constants.js
packages/cli/src/oclif/ZapierBaseCommand.js
packages/cli/src/oclif/commands/register.js
packages/cli/src/tests/register.test.js

This PR adds a minimum length constraint for an integration title when adding via zapier register.

PDE-4140 feat(cli): Integration title length must be at least 2 characters

---

packages/schema/docs/build/schema.md

docs(schema) update version mismatch

---

packages/core/src/tools/create-storekey-tool.js
packages/core/test/tools/create-storekey-tools.js

* Added a `TypeError` check for non-string cursors in `z.cursor.set()`.
Note regarding backwards compatibility: Using `z.cursor.set` with `Number`, `undefined` or `null` values results in the Zapier monolith throwing an exception. Therefore, this change is just moving the check closer to where the error is (improving the developer experience). But technically, it does break backwards compatibility 🤔 
See Jira ticket for more details and links to context: https://zapierorg.atlassian.net/browse/PDE-4304

[PDE-4304] fix(core): z.cursor.set() returns TypeError with non-string arguments

---

boilerplate/scripts/build.sh

Currently, when building the boilerplate, if it is unclean (old build files persists from previous runs), then that increases the size of the new build, which can cause issues.
This PR updates the script to remove the old build directory and recreate it before running, to make sure nothing is lingering.

[PDE-4286] fix(boilerplate): clear build directory before building

---

docs/index.html
packages/cli/README-source.md
packages/cli/docs/index.html

Copies the change in #713 back to README-source.md.

PDE-4193 docs(cli): fix broken link in README-source.md

---

docs/index.html
packages/cli/README.md
packages/cli/docs/index.html
packages/cli/snippets/paging-cursor.js

Small syntax improvement in the docs example - the previous example would throw an error if `response.nextPage` was `null` which would commonly be the case.

docs(cli): update z.cursor docs for how to handle reaching the end of the result set

---

packages/schema/docs/build/schema.md
packages/schema/exported-schema.json
packages/schema/lib/schemas/FieldSchema.js

Adds an optional property `steadyState` on the `FieldSchema` to be used with outputFields of polling triggers.
Ticket: https://zapierorg.atlassian.net/browse/PDE-4362

feat(schema): Add steadyState property on FieldSchema

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

Update the documentation on the `zapier logs` command to make clearer the fact that it defaults to the command runner's account.

 [PDE-4445] docs(CLI): Update zapier logs documentation to mention default user target

---

packages/core/src/tools/create-logger.js
packages/core/test/logger.js

This PR allows zapier-platform-core to take the `logFieldMaxLength` from the server and use it as the string length limit to truncate log fields. So we can control the truncation behaviors from the server, rather than always truncating at 3500 characters.
Also refactors the logger code to reduce some redundant computation.

PDE-4384 feat(core): add support for server-side logFieldMaxLength

---

packages/cli/src/tests/utils/convert.js
packages/cli/src/utils/convert.js

Fixes two bugs in the `zapier convert` command.
Before (current behavior):
1. When there's a syntax error in user's code (the code the developer wrote in Code Mode), `zapier convert` would fail because we didn't catch the error raised from Prettier, the code formatter used in `zapier convert`.
2. When a sample has a field named `source` (there's an example in the test code), `zapier convert` would incorrectly replace it with a function, which then would cause Prettier to error.
After (expected behavior):
1. When there's a syntax error in user's code, `zapier convert` will print an warning and carry on the conversion. It will leave the bad code as is without prettifying. ![](https://cdn.zappy.app/18bf932712f4e561269e1a74542ac1eb.png)
2. When a sample has a field named `source`, `zapier …

PDE-4495 fix(cli): `zapier convert` crashes due to syntax error in user's code and should not replace `source` in sample

---

packages/core/index.d.ts

Fixes #734, where the response of `z.request({ raw: true })` doesn't have correct method typings for TypeScript.
```typescript
import { Bundle, ZObject } from 'zapier-platform-core';
const getJson = async (z: ZObject): Promise<object> => {
const response = await z.request({
url: 'https://httpbin.zapier-tooling.com/get',
raw: true,
});
return response.json();
};
const getBuffer = async (z: ZObject): Promise<Buffer> => {
const response = await z.request({
url: 'https://httpbin.zapier-tooling.com/image/png',
raw: true,
});
return response.buffer();
};
const getText = async (z: ZObject): Promise<string> => {
const response = await z.request({
url: 'https://httpbin.zapier-tooling.com/status/418',
raw: true,
skipThrowForStatus: true,
});
return response.text();
};
const getContent = async (z: …
```

PDE-4677 fix(core): RawHttpResponse method types

---

packages/cli/package.json
packages/cli/src/tests/utils/build.js
packages/cli/src/tests/utils/files.js
packages/cli/src/utils/build.js
packages/cli/src/utils/files.js
packages/cli/src/utils/local.js
packages/cli/src/utils/misc.js
yarn.lock

Fixes #648.
Some developers may choose to structure their project using [npm workpaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces) or [yarn workspaces](https://classic.yarnpkg.com/lang/en/docs/workspaces/). An example project structure might look like:
```
(project root)
├─ package.json
└── packages/
├─ app-1/
│  ├─ index.js
│  └─ package.json
└─ app-2/
├─ index.js
└─ package.json
```
If you run `npm install` in the above example, `app-1` and `app-2` will share their dependencies in the project root's `node_modules`. Only the dependencies with version discrepancies will be placed into `app-1/node_modules` or `app-2/node_modules`.
The current implementation of `zapier build` doesn't support workspaces. It always assume it can always find `zapier-platform-core` in the working …

PDE-4678 fix(cli): `zapier build` fails with npm workspaces

---

packages/cli/package.json
packages/cli/src/oclif/ZapierBaseCommand.js
packages/cli/src/oclif/hooks/renderMarkdownHelp.js
yarn.lock

As mentioned in https://github.com/zapier/zapier-platform/pull/556#issuecomment-1171944967, simply upgrading `@oclif/plugin-help` will break CLI functionality due to certain helper methods we were using in `ZapierBaseCommand` being removed. In fact, they were moved over to the `@oclif/core` library.
This PR adds the `@oclif/core` dependency, which is also the [first step in migrating over](https://github.com/oclif/core/blob/main/guides/PRE_CORE_MIGRATION.md) from deprecated helper libraries.
A visual difference in how text is formatted can be observed before and after this PR. I'm looking into why this formatting change occurred to see if we can maintain the previous formatting style.
Before (wider terminal):
After (wider terminal): 
Before (smaller terminal):
After (smaller terminal):

[PDE-4682] chore(cli): Add @clif/core dependency, upgrade @oclif/plugin-help

---

packages/cli/scaffold/test.template.js
packages/cli/src/utils/convert.js

This fixes `zapier convert` failing (and thus rolling back) on:
```
›   Error: Identifier directly after number. (1:15)
›   > 1 | const 20151109PollTrigger = require('./triggers/20151109_poll.js');
›       |               ^
›     2 | const hookTrigger = require('./triggers/hook.js');
›     3 | const hookRawTrigger = require('./triggers/hook_raw.js');
›     4 | const hookV2Trigger = require('./triggers/hook_v_2.js');
```
and:
```
›   Error: Identifier directly after number. (13:59)
›     11 |     const bundle = { inputData: {} };
›     12 |
›   > 13 |     const results = await appTester(App.triggers.20151109_poll.operation.perform, bundle);
›        |                                                           ^
›     14 |     expect(results).toBeDefined();
›     15 |     // TODO: add more …
```

fix(cli) Don't break when converting triggers whose key start with a number

---

packages/cli/src/utils/build.js

Following up with this [comment](https://github.com/zapier/zapier-platform/pull/738#discussion_r1475061941), this PR adds some comments in the workspace handling code in `utils/build.js`.
Also replaces `path.join(workspaceRoot, relpath)` with `path.resolve(workspaceRoot, relpath)` just in case someone uses an absolute path in `<package_json>.workspaces` and `relpath` is an absolute path.

PDE-4678 fix(cli): add comments and fix a path issue in `utils/build.js`

---

packages/cli/package.json
yarn.lock

This PR follows up from https://github.com/zapier/zapier-platform/pull/739 and then https://github.com/zapier/zapier-platform/pull/743, where `@oclif/core` was installed to unblock an upgrade to `@oclif/plugin-help` but it turned out to be unnecessary.
More context: https://github.com/zapier/zapier-platform/pull/744#discussion_r1477649059

[PDE-4682] chore(cli): Remove @oclif/core dependency

---

packages/cli/src/utils/local.js

This is a followup MR for: https://github.com/zapier/zapier-platform/pull/738
We are seeing errors upon installing `v15.5.2`: `Error: Cannot find module 'zapier-platform-core'` with a stack trace pointing back to the `locals.js` file.

PDE-4678 fix(cli): Use findCorePackageDir() utility method when importing zapier-platform-core

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

Document `allowGetBody` option as discussed and confirmed in this Slack thread: 
[Hey team - any reasons why we shouldn’t document the allowGetBody option on z.request() that was originally implemented here and is mentioned in the CHANGELOG?](https://zapier.slack.com/archives/C04P5J5R8E4/p1709091636494479)

[PLATSUP-1022] Document `allowGetBody` option in `z.request()` options

---

packages/schema/docs/build/schema.md
packages/schema/exported-schema.json
packages/schema/lib/schemas/ThrottleObjectSchema.js

feat(schema): Adds support for overriding the throttle configuration based on a Zapier account attribute "EXPERIMENTAL"

feat(schema) - Add support for throttle configuration override

---

packages/schema/docs/build/schema.md
packages/schema/exported-schema.json
packages/schema/lib/schemas/ThrottleObjectSchema.js

feat(schema): Support "key" in throttle schema and the scope of "action"

feat(schema): Support "key" in throttle schema and the scope of "action"

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html
packages/cli/snippets/throttle-configuration.js

Documents changes in https://github.com/zapier/zapier-platform/pull/755 and https://github.com/zapier/zapier-platform/pull/757. Merge this only when both have been merged.

docs(cli): Update docs on throttle config object

---

packages/cli/src/oclif/hooks/getAppRegistrationFieldChoices.js
packages/cli/src/smoke-tests/smoke-tests.js
packages/cli/src/tests/register.test.js

**Mock `ZAPIER_DEPLOY_KEY` for RegisterCommand tests**
commit ac29aa2ea832e3a379b4d3b74a4c10a0b511a20b
GitHub's dependabot [doesn't have access to secrets][1]. This is why dependabot's PRs have been failing. The tests in RegisterCommand don't really need the deploy key because they use nock to mock HTTP requests. But our `callAPI()` function always checks crendentials with `readCredentials()`; it isn't aware that the request may be "nocked" and won't require a deploy key.
This commit bypasses the checks in `readCredentials()` by setting a fake `ZAPIER_DEPLOY_KEY` before running the tests. Since the requests are "nocked", the fake deploy key won't be sent to Zapier anyway.
[1]: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-acti …

PDE-3951 test(cli): fix failing tests in dependabot's PRs

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

Tiny update for missing word in CLI docs.
Does not allow users enter data. -> Does not allow users **to** enter data.

PDE-4878 docs(cli): Add missing 'to' in cli docs

---

packages/legacy-scripting-runner/exceptions.js

The addition of error traceback makes the error message an invalid JSON and the backend expects a valid JSON. So this change aligns with the current behavior in the core [here](https://github.com/zapier/zapier-platform/blob/main/packages/core/src/errors.js#L16).

fix(legacy-scripting-runner): Remove error traceback from ErrorException

---

packages/core/src/tools/create-logger.js
packages/core/test/logger.js

fix(core): Handle null response_content before passing to findSensitiveValues

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

This note becomes irrelevant with the stop to changing integrations' keys.

docs(cli): Remove note on redirect_uri change after publish

---

packages/core/package.json
packages/core/test/logger.js
yarn.lock

Fixes uncensored set-cookie header by upgrading secret-scrubber-js to 1.1.1.

PDE-4985 fix(core): censor set-cookie header

---

packages/core/integration-test/integration-test.js
packages/core/src/app-middlewares/after/checks.js
packages/core/src/checks/index.js
packages/core/src/checks/is-create.js
packages/core/src/checks/is-trigger.js
packages/core/src/checks/perform-bulk-return-type.js
packages/core/test/checks.js
packages/core/test/create-app.js
packages/core/test/tools/resolve-method-path.js
packages/core/test/userapp/index.js

Adds a runtime check `perform-bulk-return-type` to ensure the result returned by the `performBulk` function follow the requirements:
1. The returned object must contain _all_ the IDs from the input `bundle.bulk`.
2. Every sub-object in the returned object has an `outputData` object _or_ an `error` string.
I found there was no integration test that ran all the [checks](https://github.com/zapier/zapier-platform/blob/01ced32396a4f96b10609b68539e11115b07af7f/packages/core/src/checks/index.js#L2) in the [checkOutput](https://github.com/zapier/zapier-platform/blob/01ced32396a4f96b10609b68539e11115b07af7f/packages/core/src/create-app.js#L37) middleware, so I added [one](https://github.com/zapier/zapier-platform/blob/01ced32396a4f96b10609b68539e11115b07af7f/packages/core/test/create-app.js#L317). …

feat(core): add runtime check for performBulk

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html
packages/cli/snippets/bulk-create.js

docs(cli): Add docs for bulk-write support

---

packages/cli/src/utils/misc.js

This is related to `CVE-2024-27980`. See Node.js report for the full details: https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2#command-injection-via-args-parameter-of-child_processspawn-without-shell-option-enabled-on-windows-cve-2024-27980---high
This fixes #784.

[PDE-5065] cli(fix): Add `shell: true` as a default option for Windows users when running spawn() command

---

packages/schema/exported-schema.json
packages/schema/lib/schemas/CreatesSchema.js
packages/schema/lib/schemas/SearchOrCreatesSchema.js
packages/schema/lib/schemas/SearchesSchema.js
packages/schema/test/index.js

We currently have 2 tickets that have come up, reporting action keys that should be invalid:
- [PDE-4948](https://zapierorg.atlassian.net/browse/PDE-4948)
- [PDE-4889](https://zapierorg.atlassian.net/browse/PDE-4889)
I reproduced this issue via CLI, confirming it is currently possible to have an action with a `key` that's invalid (for example, `3create_tag` or `create_order:test`) per the [KeySchema](https://github.com/zapier/zapier-platform/blob/main/packages/schema/lib/schemas/KeySchema.js) and per the [CreatesSchema](https://github.com/zapier/zapier-platform/blob/main/packages/schema/lib/schemas/CreatesSchema.js) `patternProperties`.
The cause seems to be that the library we're using, `jsonschema`, expects us to set `additionalProperties: false` if we want all properties that don't …

fix(schema): Update createsSchema to disallow additional properties, improve tests [PDE-4948]

---

packages/core/package.json
packages/core/src/http-middlewares/after/prepare-response.js
packages/core/src/http-middlewares/after/throw-for-disallowed-hostname-after-redirect.js
packages/core/src/tools/create-app-request-client.js
packages/core/test/http-middleware.js
yarn.lock

As mentioned in the [work ticket](https://zapierorg.atlassian.net/browse/PDE-5063), `node-fetch` doesn't support conditional erroring on redirects. In this MR, we add an "after" middleware to check if the `z.request` experienced a redirect, and error out if the redirection ended up in a disallowed domain (currently only disallowing localhost). We need to check the `resp.url` as the `req.url` does not change on redirect.
Changes:
* Install `nock` explicitly in `core` package
* Add a `throwForDisallowedHostnameAfterRedirect` middleware and use it by default in the `httpAfters` middleware list (after `logResponse`) 
* Update `prepare-response.js` in order to surface the `resp.redirected` and `resp.url` properties for the new middleware. An alternative here could be to move the new middleware …

[PDE-5063] feat(core): Add afterResponse middleware to check if HTTP redirect is made to disallowed domain

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

Revives https://github.com/zapier/zapier-platform/pull/800.
cc @charettes

AP-3012 docs(cli): document performResume default implementation

---

packages/core/src/app-middlewares/before/z-object.js
packages/core/src/tools/create-lambda-handler.js
packages/core/test/create-app.js
packages/core/test/userapp/constants.js
packages/core/test/userapp/index.js

Based on the POC patch logic here: https://gitlab.com/zapier/zapier/-/merge_requests/57310/diffs#note_1923825583
`z.require('./constants')` should work relative to the app root rather than to `node_modules/zapier-platform-core/src/app-middlewares/before`.

feat(core): Allow relative paths via z.require() [PDE-5116]

---

packages/core/package.json
packages/core/src/app-middlewares/after/large-response-cacher.js
packages/core/src/tools/cleaner.js
packages/core/src/tools/create-file-stasher.js
packages/core/src/tools/create-response-stasher.js
packages/core/src/tools/uploader.js
packages/core/test/app-middleware.js
packages/core/test/tools/response-stasher.js
packages/core/test/userapp/index.js

https://zapierorg.atlassian.net/browse/PDE-5125
This PR addresses a new event field: `autostashPayloadOutputLimit` that we can process.
If this value is set from the backend, we can conditionally stash the payload response. This is to work around the Lambda 6mb output limit. 
There are some changes as well to refactor some things around, as we will be reusing the `uploader()` functionality to stash the payload.

PDE-5125 - feat(core) Handle large response payloads

---

packages/core/integration-test/integration-test.js
packages/core/src/tools/create-lambda-handler.js

Allow `loadApp` to default to a CLI integration's definition when no definition override (for Platform UI apps) is passed, so that the partial definition of the external action gets merged in.

feat(core): Update loadApp to default to CLI definition and merge in external action definition as needed [PDE-5114]

---

packages/core/src/tools/wrap-hydrate.js
packages/core/test/hydration.js

Increases the hydration payload limit. In older Node versions, this was capped at 8kb due to the hydration URL that we need to call eventually. Since Node 16, this is now 16kb.

PDE-5159 feat(core) - Increase hydration payload limit

---

packages/core/integration-test/integration-test.js
packages/core/src/tools/create-lambda-handler.js

The `extendAppRaw` function in `createLambdaHandler` currently assumes it should always/only concatenate arrays in an app definition. However, for many cases we actually do want to override the array, not concatenate it - for example for inputFields coming in from an external action, we should fully overwrite the base inputFields with the partial inputFields.

feat(core) Update extendAppRaw to override arrays as well as objects [PDE-5114]

---

packages/core/integration-test/integration-test.js
packages/core/src/tools/create-lambda-handler.js

MR [57964](https://gitlab.com/zapier/zapier/-/merge_requests/57964) and [57983](https://gitlab.com/zapier/zapier/-/merge_requests/57983) are temporary fixes. This one is the long-term fix.

PDE-5114 fix(core): prevent standalone 'creates' in `extension` from colliding with resource keys in `base`

---

.github/pull_request_template.md
ARCHITECTURE.md
CONTRIBUTING.md
README.md
package.json

* ~~Added `schema-to-ts` to `workspaces` key in the root `package.json`, so that running `yarn` from the root of the repo installs `schema-to-ts` packages as well.~~
* Without this, running `yarn` and then `yarn test` would result in errors around the `vitest` package missing as part of the `(cd schema-to-ts && yarn test)` part.
* Updated some docs to mention `schema-to-ts`

docs(schema-to-ts): [PDE-5969] Minor doc updates to reference schema-to-ts package

---

packages/core/src/app-middlewares/after/large-response-cacher.js
packages/core/src/tools/create-response-stasher.js
packages/core/src/tools/uploader.js
packages/core/test/app-middleware.js
packages/core/test/tools/response-stasher.js
packages/core/types/zapier.generated.d.ts

Currently when using this autostashing payload feature, if the perform call returns non-ascii characters, it won't stash. This MR encodes the data before uploading and we can decode on the way out. 
Planning to release this on 15.11.1, so the backend should account for this by only decode when zpc@15.11.1.

PDE-5184 fix(core) - Add base64 encoding before uploading to s3

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

Documents this change: https://gitlab.com/zapier/zapier/-/merge_requests/58080

PDE-5189 docs: document `bundle.meta.withSearch`

---

packages/core/types/index.test-d.ts
packages/core/types/zapier.custom.d.ts

This allows for `beforeRequest`/`afterResponse` middleware functions to be asynchronous, which is reasonably common in the integration monorepo ([Xero example](https://gitlab.com/zapier/team-integrations/zapier-platform-integrations/-/blob/3f539106d79b8c6a7a4a58470eeabaabe85996fd/apps/xero/middleware.js#L92))

fix(core): Allow Async Middleware Functions Types

---

packages/schema/lib/functional-constraints/labelWhenVisible.js

Small change to add `bulk_reads` to the functional constraint which validates the `display` property. 
It's a minor thing I discovered while adding schema validation for external actions. Currently it's possible to have a `bulk_read` action type with a partially complete display property 😨

Add bulk_reads to display functional constraint

---

packages/schema/lib/functional-constraints/labelWhenVisible.js

[The previous MR](https://github.com/zapier/zapier-platform/pull/829) to add bulk reads to schema validation used snake case - this corrects it to use camel case

Correct casing on bulk reads action type

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

Be more accurate and specific on the limitation of the `primary: true` setting.
Previous PR: https://github.com/zapier/zapier-platform/pull/834

PDE-5230 doc(cli): be more accurate on limitation of `primary: true`

---

packages/core/types/zapier.generated.d.ts
schema-to-ts/src/precompile.ts

This removes length-enforced tuples types with spread parameters that are difficult and annoying to write in separate declarations.
```typescript
const choices: [FieldChoiceWithLabel, ...FieldChoiceWithLabel[] = [...]
```
becomes just:
```typescript
const choices: FieldChoiceWithLabel[] = [...]
```
cc @cvanderkolk

fix(schema-to-ts): Simplify Array types (IQQ-1490)

---

packages/core/types/zapier.custom.d.ts

Minor fix to help with HTTP Option typing, notably `.params` in middleware.

fix(types): Fix HTTP Option types that used `object`

---

packages/core/types/zapier.generated.d.ts
packages/schema/exported-schema.json
packages/schema/lib/schemas/BasicHookToPollOperationSchema.js

Adds a new optional field for "hook to poll" triggers.
`maxPollingDelay` represents the value (in seconds) to set for the poll part.

feat(schema) Add configurable poll delay for HookToPoll

---

packages/core/types/index.test-d.ts
packages/core/types/zapier.custom.d.ts

This is a sanctioned object that can be used freely for extra middleware options etc. without needing to bend over backwards to support patching the `z.request` options

chore(types): Add `customOptions` field to z.request options

---

packages/core/src/tools/create-cache.js
packages/core/test/tools/create-cache.js

Internal: Adds an scope option to z.cache. Currently it uses scope internally with user and auth only. We may want to exercise one or the other only so providing this flexibility from the interface.

feat(core) - Add scopes as an option for zcache usage

---

docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html
packages/core/src/tools/request-client.js

As Cass reported [here](https://zapier.slack.com/archives/C5Z9BP4U9/p1725954040992739), `node-fetch` supports the `signal` option described here: https://www.npmjs.com/package/node-fetch#request-cancellation-with-abortsignal. Looks like this is supported after Node 8 and replaces `timeout` (although timeout still seems to be supported), according to these comments: https://github.com/node-fetch/node-fetch/tree/2.x?tab=readme-ov-file#options
However, we have not added that to the request options for `z.request`. This PR aims to add that per Fokke's suggestion that we may just need to add it to this picklist.

feat(core): Add node-fetch feature `signal` to request client [PDE-5367]

---

packages/schema/docs/build/schema.md

Lefthook developers tried using the `inputFormat` field property for an action input field and the copy to clipboard field that renders in the Editor is not well suited for action step as it disables the ability to map a value to the field. Noting this in the docs explicitly. Slack thread with editor team [here](https://zapier.slack.com/archives/C02TQNXKEBF/p1725870227224329?thread_ts=1725653551.771619&cid=C02TQNXKEBF).

[PARTOPS-1224] docs(schema) - Add additional details to inputFormat property in fieldSchema

---

packages/core/src/tools/create-logger.js
packages/core/test/logger.js

When invoking methods like authentication.oauth1Config.getAccessToken or authentication.oauth2Config.refreshAccessToken, some servers return querystring formatted data containing secrets. We should censor those properly in HTTP logs.

fix(core): Censor OAuth1 getAccessToken HTTP logs [PDE-5390]

---

INSTALL_DEV.md
README.md

PDE-5321 doc: add instructions of how to install development version

---

packages/core/types/zapier.custom.d.ts

Simply adds the occasionally used `z.errors.ResponseError` to the typing declarations.

chore(types): Add missing ResponseError Type

---

packages/cli/src/utils/convert.js

`zapier` convert is not writing `bulkReads` to their own files with tests, like it does for the other types.
This PR fixes that.
Jira: https://zapierorg.atlassian.net/browse/IP-353

fix(cli) Write bulkReads to separate files

---

CHANGELOG.md
docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html
packages/cli/package.json

- Update links in changelog
- Fix typos in README on `invoke` command
- Add a changelog item on zapier-platform-cli not supporting Node.js 16
- Bump `engines.node` from `>=16` to `>=18` for zapier-platform-cli

docs: fix typos, update docs and links

---

docs/cli.html
docs/cli.md
docs/index.html
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/cli.html
packages/cli/docs/cli.md
packages/cli/docs/index.html
packages/cli/src/oclif/commands/pull.js
packages/cli/src/oclif/oCommands.js

Some docs about the [`zapier pull`](https://platform.zapier.com/reference/cli#pull) command are on https://platform.zapier.com but not in this repo. This PR backports those contents.

PDE-5323 docs(cli): sync CLI docs, backporting docs for `pull`

---

CHANGELOG.md
packages/cli/package.json

Let's not bump `engine` in `packages/cli/package.json` until the next major release (v16).

docs(cli): revert `engine` from node 18 to 16 and soften changelog writing

---

docs/index.html
package.json
packages/cli/README-source.md
packages/cli/README.md
packages/cli/docs/index.html

Explain why hidden triggers for dynamic dropdowns need to declare input fields.
See https://zapier.slack.com/archives/C053ZLBM4SV/p1728630326891899?thread_ts=1728427664.388689&cid=C053ZLBM4SV

docs(cli) Explain why hidden triggers for dynamic dropdowns need to declare input fields #886

---

packages/core/types/index.test-d.ts
packages/core/types/zapier.custom.d.ts

This adds generic parameters to the `HttpResponse` and `RawHttpResponse` types that allow them to specify what they're returning. If not provided the default is `any`, similar to the previous behaviour.
```ts
interface User {
id: numner,
name: string,
}
const resp = await z.request<User>('https://example.com/users');
resp.data.firstName // Error: Type `firstName` doesn't exist on type User, did you mean `name`.
```
---
Because of [this note](https://github.com/zapier/zapier-platform/blob/main/packages/cli/README.md#bundletargeturl) in the CLI docs, I've also marked the `.json` attribute on `HttpResponse` objects as `@deprecated`. It will now show up in the editor struck out, and suggest using `.data` instead. Is this deprecating `.json` correct in your opinion?

feat(types): Type z.request responses; deprecate `.json`

---

example-apps/typescript/src/authentication.ts
example-apps/typescript/src/constants.ts
example-apps/typescript/src/creates/movie.ts
example-apps/typescript/src/index.ts
example-apps/typescript/src/middleware.ts
example-apps/typescript/src/test/creates.test.ts
example-apps/typescript/src/test/triggers.test.ts
example-apps/typescript/src/triggers/movie.ts
example-apps/typescript/tsconfig.json
packages/cli/src/generators/templates/typescript/src/authentication.ts
packages/cli/src/generators/templates/typescript/src/constants.ts
packages/cli/src/generators/templates/typescript/src/creates/movie.ts
packages/cli/src/generators/templates/typescript/src/index.ts
packages/cli/src/generators/templates/typescript/src/middleware.ts
packages/cli/src/generators/templates/typescript/src/test/creates.test.ts
packages/cli/src/generators/templates/typescript/src/test/triggers.test.ts
packages/cli/src/generators/templates/typescript/src/triggers/movie.ts
packages/cli/src/generators/templates/typescript/tsconfig.json
packages/core/types/zapier.custom.d.ts

This upgrades the `zapier init` TypeScript example (and the example reference application as well) to use a much closer to real-world OAuth2 example configuration with scopes and `API_URL` constants.
A minor tweak was made to the Before and After Middelware types to make the arguments provided no longer optional, as they are always present.

feat(cli): Add OAuth to TS init output [IQQ-1860]

---

packages/cli/src/smoke-tests/smoke-tests.js

Fixes a failing smoke test on the CLI package size. CLI is actually much smaller now since many docs are deleted. We may want to bump the ratio from 0.5 back to 0.7 after we release the next version.

PDE-5460 test(cli): CLI is actually much smaller now since many docs are deleted

---

packages/core/src/tools/create-cache.js
packages/core/test/tools/create-cache.js

Adds nx argument to z.cache.set().
**NOTE:** `z.cache.set()` is still for internal usage.

feat(core) Adds nx argument to z.cache.set()

---

packages/core/src/tools/create-lambda-handler.js
packages/core/src/tools/memory-checker.js

See related Slack thread: https://zapier.slack.com/archives/C04P5J5R8E4/p1729720807731419?thread_ts=1729271444.276339&cid=C04P5J5R8E4
You can recreate the `EMFILE` error locally like:
```js
const fs = require('fs');
const path = require('path');
// Path to a file you want to repeatedly open (can be any existing file)
const filePath = path.resolve(__dirname, 'testfile.txt');
// Ensure the test file exists
fs.writeFileSync(filePath, 'This is a test file.');
const openFiles = [];
function openFileRepeatedly() {
try {
// Attempt to open a file repeatedly without closing it
for (let i = 0; i < 10000000; i++) {
const fd = fs.openSync(filePath, 'r');
openFiles.push(fd);
console.log(`Opened file descriptor ${fd}`);
}
} catch (err) {
console.log(`Error code: ${err.code}`)
console.error(`Error …
```

fix(core): [PDE-5470] Force exit process on EMFILE error inside checkMemory

---

packages/core/src/tools/create-http-patch.js
packages/core/src/tools/http.js
packages/core/test/tools/create-http-patch.js

Fixes an issue where a late listener of a third-party library (like aws-sdk v3) attached to HTTP response stream could miss data chunks that were already consumed by our HTTP logger. The fix involves:
1. Replacing direct `response.on('data')` listener with a patched `emit` function so that we don't attach a listener earlier than any other listeners
2. Maintaining the original event emission behavior by calling the original `emit` with all arguments
3. Adding a test that verifies:
- Late listeners receive complete data without missing bytes
- Logger captures the complete response as expected
The changes also include:
- Adding `text/plain; charset=utf-8` to allowed content types
See also this [video](https://zapier.slack.com/archives/C5Z9BP4U9/p1730112195116519) (internal-only) to walk …

fix(core): HTTP patch breaks aws-sdk v3 (or other libraries) intermittently

---

packages/cli/src/oclif/commands/invoke.js
packages/core/src/tools/create-lambda-handler.js

While working on #905, I noticed that `zapier invoke --debug` didn’t print HTTP logs for requests not sent by `z.request()`. This happened because the HTTP patch (`packages/core/create-http-patch.js`) wasn’t applied, as the CLI client set `event.calledFromCli` to true before calling an app command. The `event.calledFromCli` flag has existed for a long time, initially based on the assumption that we wouldn’t need to patch native `http` and `https` Node.js modules when running app commands from the local CLI. However, this assumption no longer holds now with the `invoke` command.
To avoid changing behavior in existing platform-core versions, I'm keeping `event.calledFromCli` set to true for the `invoke` CLI command, and introducing a new flag, `event.calledFromCliInvoke`, so platform-core …

PDE-5488 fix(cli): `zapier invoke --debug` should print non-z.request http logs

---

packages/cli/src/smoke-tests/smoke-tests.js

We can revert #899 now that the smaller CLI package (v15.18.0) has been released.

PDE-5460 test(cli): more strict assertion on CLI package size in smoke tests

---

packages/core/src/tools/create-lambda-handler.js

In debugging some apps, it seems like sometimes lambdas may be hanging indefinitely until the timeout expires.
This causes the action to fail, even if all the app code has completed. 
Debugging further it looks like it's possible that when processing larger datasets, some open connections will be kept open and block the event loop from clearing. 
This heuristic is something we can add from Lambda
https://docs.aws.amazon.com/lambda/latest/dg/nodejs-context.html
the gist is, if we set `context.callbackWaitsForEmptyEventLoop = false;` then once the callback is called, we exit, despite having other connections
https://zapierorg.atlassian.net/browse/PDE-5490

feat(core) - PDE-5490 calling lambda callback doesnt wait for event loop

---

packages/legacy-scripting-runner/package.json
yarn.lock

Node.js v18 in Lambda removed implicit `aws-sdk v2` support, see: https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/
Certain apps that depend on `legacy-scripting-runner` use the `AWS` object, so a safe solution is to explicitly install and require `aws-sdk` for this package.
See Slack context: https://zapier.slack.com/archives/C04QN139NV6/p1730737223650609?thread_ts=1730491575.645539&cid=C04QN139NV6

fix(legacy-scripting-runner): [PDE-5515] Install `aws-sdk v2`  for legacy-scripting-runner

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/package.json

- :hammer: Add `aws-sdk v2` to dependency list ([#912](https://github.com/zapier/zapier-platform/pull/912))

chore(legacy-scripting-runner) Release legacy-scripting-runner v3.8.13

---

packages/legacy-scripting-runner/package.json
yarn.lock

This reverts commit a35081b39f4890f8b9e72013d0cdedf32eca3f66.
Bundling in `aws-sdk` really bloats the boilerplate zip file so we're going to tackle this problem on an integration-by-integration basis. See Slack thread for details: https://zapier.slack.com/archives/C5Z9BP4U9/p1731506889913249?thread_ts=1731431960.425939&cid=C5Z9BP4U9

chore(legacy-scripting-runner): [PDE-5515] Revert "Install aws-sdk v2 for legacy-scripting-runner"

---

packages/core/src/tools/create-dehydrator.js
packages/core/test/hydration.js
packages/core/types/zapier.custom.d.ts

feat(core): Add support for providing the cache expiration for hydrators

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/package.json

- :bug: Revert `aws-sdk v2` bundling change from 3.8.13 ([#916](https://github.com/zapier/zapier-platform/pull/916)). This release is essentially the same as 3.8.12.

chore(legacy-scripting-runner) Release legacy-scripting-runner v3.8.14

---

packages/core/types/zapier.custom.d.ts

This updates the `bundle.meta` types with clearer docs, deprecation markings, and support for the new `timezone` and `withSearch` fields.
I've followed the [Core Docs](https://docs.zapier.com/platform/build-cli/core#bundle-meta) on this subject, but if anything is not strictly correct with the platform's behaviour I'll be happy to adjust.
- Deprecated `meta.zap`, and all of the inner `id`, `user`, and `user.timezone` properties
- Deprecated `isTestingAuth`, because the docs say "Legacy property".
- Added `withSearch: string | undefined`. Docs unclear if this is always set and will be `string | undefined`, or _if_ the key is present it will be a valid string, meaning `withSearch?: string` would be better.
- Added `timezone: string | null`. Same as above.
- `isBulkRead`: Unchanged, but …

chore(ts): Update bundle.meta typings [IQQ-2105]

---

packages/core/types/zapier.custom.d.ts

This extends the `HttpRequestOptions` interface with a variant with a concrete `url` explicitly set, which is used in some invocations of `z.request`, but also in before middleware.

chore(ts): Extract HttpRequestOptionsWithUrl, add to middleware

---

packages/cli/src/oclif/hooks/renderMarkdownHelp.js

The markdown formatting doesn't seem to work in the release-16.0.0 branch. This PR fixes that. The reason is that the new version of marked-terminal changes its interface that we need to adapt.
---
---
---
---
P.S. I don't like the extra new lines in the EXAMPLES section. Those seems to be [hard-coded](https://github.com/oclif/core/blob/9ed5f726a57f7c9e01ec991ed605340a9dc21151/src/help/command.ts#L146) in the new oclif, so 🤷 .

PDE-4089 fix(cli): fix command help markdown formatting

---

example-apps/dynamic-dropdown/.gitignore
example-apps/dynamic-dropdown/README.md
example-apps/dynamic-dropdown/package.json
example-apps/dynamic-dropdown/triggers/people.js
example-apps/dynamic-dropdown/triggers/species.js
packages/cli/src/generators/templates/dynamic-dropdown/README.md
packages/cli/src/generators/templates/dynamic-dropdown/triggers/people.js
packages/cli/src/generators/templates/dynamic-dropdown/triggers/species.js

https://swapi.dev is down. It has been down at least twice as far as I can remember. I found https://swapi.info seems to be a more reliable site. Let's move to that.

PDE-5506: fix(cli): move swapi.dev to swapi.info for dynamic-dropdown template

---

packages/core/src/tools/fetch-logger.js
packages/core/test/tools/fetch-logger.js

Platform-core creates a logger instance on every Lambda invocation:
https://github.com/zapier/zapier-platform/blob/98fa8a60cd6c4572f3517e58e982368ffeb1e74a/packages/core/src/tools/create-lambda-handler.js#L217-L218
The logger instance should not be reused across Lambda invocations. The logger instance is bound to an event, the input payload of a Lambda invocation. And the event contains the log extra fields, including `execution_id`, `invocation_id`, `zap_id`, etc. If the logger instance is unfortunately reused, the log can use old values for those fields from a previous Lambda invocation. This is what happened to Webflow, which [uses native fetch](https://github.com/webflow/js-webflow-api/blob/472bac9a5d43b9a15c96b9d7bb96ebe36341b738/src/core/fetcher/getFetchFn.ts#L9) in its …

PDE-5550 fix(core): native fetch patch should not reuse logger instance across Lambda calls

---

packages/cli/src/oclif/ZapierBaseCommand.js
packages/cli/src/utils/analytics.js
packages/cli/src/utils/api.js

This pull request expands the analytics functionality in the Zapier CLI by updating the way arguments are recorded and adding additional information to the analytics payload.
- **Updated `analytics.js`**:
- Included `app_id` in the analytics payload, which is fetched from the linked app configuration OR integrationid" in arguments since some commands ( like "zapier convert" ) won't have a linked app directory when called. 
- **Updated `ZapierBaseCommand.js`**:
- Change `Object.keys(this.args)` to `this.args`. This allows us to later capture app ID argument value based on the name and populate `numArgs` and parts of `flags` . This is not meant to capture `this.args` in analytics as shown in tests below 
The inclusion of app ID will provide better insights into CLI usage patterns. There is …

PDE-5636 feat(cli): include extra fields for analytics 

---

packages/cli/src/oclif/commands/history.js

This small PR adds a `version` column when running `zapier history`. The main reason being that, for environment variable add/delete actions, we don't display information on which AppVersion was affected which is an important factor when debugging. This does bloat the `"version added"` and `"version changed"` history logs because those already store the version as part of the `"message"` field...
Before:  
After:

[PDE-5644] cli(fix): Include "version" column when fetching history logs

---

packages/cli/src/utils/analytics.js

Capture the argument + flags keys ( no values ) that are being used
Related MR: https://gitlab.com/zapier/zapier/-/merge_requests/60772

PDE-5641: feat(core) capture CLI arguments in analytics safely

---

packages/cli/src/constants.js

[PDE-5692] fix(CLI): Integration check reference URL's anchor tags are broken

---

packages/cli/docs/cli.md
packages/cli/src/oclif/commands/env/set.js
packages/cli/src/oclif/commands/env/unset.js
packages/cli/src/utils/api.js

The idea here is to provide a bit of a warning for a potentially dangerous operation for live app versions. In fact, UI integrations can't update env vars for production versions at all, so it makes sense to add a buffer here for CLI integrations.
Since `is_production` is a backend check, let's react to a specific HTTP status and let the user know how to override via `--force`.  I'm not using `this.confirm` (similar to [user:add](https://github.com/zapier/zapier-platform/blob/4f55292cdb2b5a7d890fbb40c877c1a7c3922587/packages/cli/src/oclif/commands/users/add.js#L11)) since  having users re-write the command with the added flag is even stricter.
See related backend MR: https://gitlab.com/zapier/zapier/-/merge_requests/60723

[PDE-5660] feat(cli): Require `--force` flag when updating production integration version environment variables via `env:set` or `env:unset`

---

packages/cli/docs/cli.md
packages/cli/src/oclif/commands/migrate.js
packages/cli/src/oclif/commands/promote.js

This PR adds logic to run soft-checks before promote/migration via a new backend endpoint. Upon receiving an `HTTP 409` from the backend, the CLI will confirm the user's intent before proceeding.

[PDE-5602] feat(cli): Add support for running pre-checks via API before promotion and migration

---

packages/cli/src/oclif/commands/env/unset.js

Caught another issue when testing locally: the error response for `env:unset` upon hitting an HTTP 409 does not specify how to solve the issue. This is because the third parameter to `callAPI` defaults as `false` ([source](https://github.com/zapier/zapier-platform/blob/575fef5d196410d601dcf23a8a811599ef689a0b/packages/cli/src/utils/api.js#L55), `env:set` has this as `true`) and the error is handled differently.
This is something to merge in before [releasing 16.2.0](https://github.com/zapier/zapier-platform/pull/953) 😅 
Before
After

[PDE-5660] fix(cli): Pass in `rawError=true` when catching error response in `env:unset`

---

packages/cli/src/generators/pull.js

A point of feedback regarding `zapier pull` is that the `ynarxdeiH` options shown during file conflicts are not user-friendly.
It's not a simple change to modify yeoman-environment's prompts ([source](https://github.com/yeoman/environment/blob/08d00cbbfa15ed12761500292b3038686fbf64fd/lib/util/conflicter.js#L322)) so the next best thing is likely to better document how to expand the options.
Before:
---
After:
---
When expanding help text by pressing enter:

[PDE-5714] docs(cli): Update `zapier pull` prompt to clarify complex `ynarxdeiH` options during file conflicts

---

packages/cli/package.json
packages/cli/src/oclif/commands/push.js
packages/cli/src/utils/api.js

This PR is similar to https://github.com/zapier/zapier-platform/pull/942, where we added a `--force` option to `env:set` and `env:unset`. 
In this MR, we add a `--overwrite-partner-changes` flag to force a `zapier push` to skip a new check when the user is a Zapier staff and the latest integration version contains partner-pushed code ("clobbering" protection).

[PDE-5716] feat(cli): Require `--overwrite-partner-changes` flag when a `zapier push` from staff could impact partner changes

---

packages/core/types/zapier.generated.d.ts
packages/schema/docs/build/schema.md
packages/schema/exported-schema.json
packages/schema/lib/schemas/AuthFieldSchema.js
packages/schema/lib/schemas/InputFieldSchema.js
packages/schema/lib/schemas/OutputFieldSchema.js

With the /FieldSchema now hidden, its references are displayed `undefined` in https://github.com/zapier/zapier-platform/blob/f59896291048bfe858e967689eabe86c58133c35/packages/schema/docs/build/schema.md#inputfieldschema

fix(schema): Reference the proper FieldSchema as necessary

---

packages/cli/src/oclif/commands/invoke.js

For string `connectionLabel`, running `zapier invoke auth test` prints the output of the `Authentication.test` results. 
For `zapier invoke auth label`, this returns an error: `Error: bundle is not defined`. While the two are similar, in that calls `testAuth`, the `label` option has additional template rendering where it looks for `bundle` and the `testResult` value does not. 
To fix, wrap the data in a bundle object.

fix(cli) - Fix invoke auth label 

---

packages/core/src/tools/create-rpc-client.js
packages/core/test/tools/mocky.js
packages/core/test/tools/rpc-client.js

We see `Got id undefined but expected ID_NUMBER when calling RPC` errors when it comes to RPC endpoints returning a 500 response. Inspecting the code, I believe we should likely catch the error before we check `res.content.id`.
After this change is released, we should update our log stream alarms to ALSO consider the `Unable to reach the RPC server` text instead of just the `Got id ${res.content.id} but expected ${id} when calling RPC` text. Both texts should be viable since we could have apps still running on previous versions.

PDE-5774 fix(core): Catch HTTP 500 along with status codes >500 in RPC client

---

packages/cli/src/utils/build.js
packages/cli/src/utils/local.js
packages/cli/src/utils/zapierwrapper.js
packages/core/include/zapierwrapper.mjs
packages/core/test/zapierwrapper.js

Summary:
* Make `zapierwrapper.mjs` statically analyzable
* Add unit tests for `zapierwrapper.js` and `zapierwrapper.mjs`
* Remove the hard-coded `index.js` from `getLocalAppHandler()`
I found that `zapier build` produced bad `build.zip`. It could miss the entry point specified in the `exports` field in the integration's `package.json`.
Why? `zapierwrapper.mjs` previously passed a variable to `import()` that couldn't be [statically analyzed](https://esbuild.github.io/api/#non-analyzable-imports) by esbuild. This PR updates it to use a placeholder string (`{REPLACE_ME_PACKAGE_NAME}`) that gets replaced with the integration package name during the build process. This allows for proper static analysis by esbuild.
This PR adds test coverage for both `zapierwrapper.js` and `zapierwrapper.mjs`. …

PDE-5244 fix(cli,core): make zapierwrapper.mjs statically analyzable, more test cases

---

packages/cli/src/oclif/ZapierBaseCommand.js

While working on #982, I noticed `zapier` CLI commands aren't showing the location of a syntax error in the integration code, even if `--debug` is enabled. Example:
```
$ zapier describe --debug
✖ Fetching integration info
›   Error: Unexpected identifier 'authentication'
```
This appears to be a regression introduced by #890. The newer version of oclif uses namespace `oclif:` [by default](https://github.com/oclif/core/blob/e788c037920b586b06bb1cd6ccccff87da7784f2/src/logger.ts#L6-L8) for the [`debug`](https://www.npmjs.com/package/debug) package. By adding `oclif:zapier:*` to `require('debug').enable()`, the detailed info is back:
```
$ zapier-dev describe --debug
oclif:zapier:describe argv is [] +0ms
oclif:zapier:describe args are {} +0ms
oclif:zapier:describe flags are { debug: true, …
```

PDE-5888 fix(cli): location of SyntaxError not showing even if --debug is on

---

packages/schema/lib/constants.js
packages/schema/test/readability.js

This PR is similar to https://github.com/zapier/zapier-platform/pull/947 in terms of fixing doc URL and anchor tags, but here we target the schema validation error link.
```js
const { makeDocLink } = require('./lib/utils/links')
makeDocLink('fieldschema')
'https://github.com/zapier/zapier-platform/blob/zapier-platform-cli%4016.3.1/packages/schema/docs/build/schema.md#fieldschema'
```
The new docs on https://docs.zapier.com/ don't host the schema reference. It instead links out to the GitHub schema page. So this PR also modifies the URL to now reference the GitHub source.

[PDE-5913] fix(schema): Update schema doc url template to reference GitHub markdown

---

packages/cli/docs/cli.md
packages/cli/src/oclif/commands/deprecate.js
packages/cli/src/utils/api.js

This MR adds a confirmation step to `zapier deprecate`. It also uses the existing `user_count` property of an app version to highlight to users if a particular app version has any active Zaps which should probably be migrated before deprecation.
CLI Demo running locally:

[PDE-5886] feat(cli): Add warning to `zapier deprecate` command

---

packages/cli/docs/cli.md
packages/cli/src/oclif/commands/legacy.js
packages/cli/src/oclif/commands/versions.js
packages/cli/src/oclif/oCommands.js

`legacy` is a new lifecycle state for app versions we want to support.
Accompanying documentation can be found [here](https://gitlab.com/zapier/public-api/public-api-docs/-/merge_requests/56)

feat(cli) - Add new zapier legacy command

---

packages/core/types/zapier.generated.d.ts
packages/schema/docs/build/schema.md
packages/schema/exported-schema.json
packages/schema/lib/schemas/PlainInputFieldSchema.js

The `computed` property was removed from `PlainInputFieldSchema` [in this PR](https://github.com/zapier/zapier-platform/pull/957/files/dc34ca28b552760fc96ec59a027005bc0311eb95#r1935694769). However, after some testing, we've identified that it is actually a valid option for certain internal use cases for input fields, and needs to be added back in order for these to continue working. More context [in the ticket](https://zapierorg.atlassian.net/browse/PDE-6056).

fix(schema): Re-add computed prop to inputFieldSchema [PDE-6056]

---

packages/core/src/http-middlewares/before/add-query-params.js
packages/core/test/http-middleware.js

This change allows `z.request()` to take an `encodeURIComponent` function that will be used to encode special characters in the request query parameters.
Example:
```js
const response = await z.request({
url: 'https://httpbin.org/get',
params: {
special: '!*()[]',
},
encodeURIComponent: (s) => {
// The built-in encodeURIComponent() function doesn't encode '!*()'
return encodeURIComponent(s)
.replaceAll('!', '%21')
.replaceAll('*', '%2A')
.replaceAll('(', '%28')
.replaceAll(')', '%29');
},
});
```
Internally, `z.request()` [uses `querystring.stringify()`](https://github.com/zapier/zapier-platform/blob/43f0abbf20d08270716cd56904390e551cc162c4/packages/core/src/http-middlewares/before/add-query-params.js#L17) to encode query parameters. It allows you to [pass in an `encodeURIComponent` …

PDE-6084 feat(core): `z.request()` accepts `encodeURIComponent`

---

packages/cli/docs/cli.md
packages/cli/src/oclif/commands/versions.js

Deprecated versions are not active versions, and are not actionable. We can remove it from the list of versions to reduce complexity. Optionally, devs can pass in an `--all` flag to list everything

refactor(cli) - zapier versions filter out deprecated by default

---

packages/core/src/tools/create-http-patch.js
packages/core/src/tools/http.js
packages/core/test/tools/create-http-patch.js

Fixes a bug where sometimes `request_data` displays as `<unsupported format>` in logs even when the request `content-type` is `application/json` or some other loggable types.

PDE-5551 fix(core): sometimes `request_data` is `<unsupported format>` in logs even when `content-type` is json

---

packages/cli/src/version-store.js
packages/core/src/tools/create-lambda-handler.js

We discovered a bug where `zapier build` (and therefore `zapier push`) hangs indefinitely on the `Building app definition.json` step if:
- The user is running `zapier-platform-cli` on v16.5.1 or lower (basically, anything lower than v17)
- The integration's `zapier-platform-core` dependency has been updated to v17.0.0
These versions can be verified by running `zapier --version` within an integration directory.
**An intermediate fix is to update the CLI to v17 by running `npm install -g zapier-platform-cli@latest` to upgrade to CLI v17.** 
Older versions of the Zapier Platform CLI rely on providing a callback to `app.handler`, e.g. [in this code block](https://github.com/zapier/zapier-platform/blob/2e24fda659f2e62fff037d13da6b6de3be10b447/packages/cli/src/utils/build.js#L237-L253). This …

fix(core): Fix CLI v16 and Core v17 incompatibility [PDE-6131] 

---

eslint.config.cjs
packages/core/index.mjs
packages/core/package.json

This fixes issues where downstream apps can't access members of the zapier library via deconstructed import statements.
V17 can cause issues with the combination of trying to use destructured imports (i.e. `import {name} from 'zapier-platform-core`), from esm modules, while zapier-platform-core remains a CJS library. This adds a shim ES interface to the module, and updates package.json to use it when being consumed by ES modules.
```shell
$ zapier init ts-esm-test --template typescript -m esm
$ cd ts-esm-test && npm install
$ zapier build
```

fix(core): Provide named esm exports of zpc objects

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/test/example-app/index.js
packages/legacy-scripting-runner/test/integration-test.js
packages/legacy-scripting-runner/zfactory.js

In legacy scripting, if you write:
```
KEY_poll: function(bundle) {
bundle.request.url = 'https://httpbin.org/get';
bundle.request.params = { foo: 'bar' };
var response = z.request(bundle.request);
var data = z.JSON.parse(response.content);
return [data];
},
```
The expected behavior should be you see an HTTP log with `request_params` being set:
```jsonc
{
"message": "200 GET https://httpbin.org/get",
// ...
"request_params": { "foo": "bar" },
// ...
}
```
But in the current behavior the log doesn't have `request_params`.

PDE-6124 fix(legacy-scripting-runner): sync `z.request()` should log `request_params`

---

packages/cli/src/generators/templates/typescript/src/authentication.ts

After running `zapier init ts-example -t typescript`, `npm install`, and `zapier push`, we expect the authentication should just work when testing in the Zap editor. But the `getAccessToken` and `refreshAccessToken` methods are implemented incorrectly. This PR fixes it.

PDE-6135 fix(cli): `typescript` project template OAuth2 doesn't work out of box

---

packages/legacy-scripting-runner/package.json

- :bug: sync `z.request` should log `request_params` ([#1017](https://github.com/zapier/zapier-platform/pull/1017))

PDE-6124 chore(legacy-scripting-runner): release 3.8.16

---

.github/workflows/ci.yaml
packages/cli/src/utils/build.js

PDE-6136 fix(cli): `zapier build` misses files on Windows

---

packages/cli/src/utils/local.js

We should also make sure using `require()` works with Windows!
This fix is slightly different from the `import()` fix because:
- `path.resolve()` is able to handle Windows paths
-  `require()` can handle Windows paths (docs: https://nodejs.org/api/modules.html#requireid) including forward and back-slashes, so we don't have to replace them like we do for `import()`

fix(cli): Make sure `loadAppRawUsingRequire` also works with Windows [PDE-6136]

---

packages/cli/src/generators/index.js

Now that we have ESM support for the Minimal and Typescript templates, ESM should be the default module type for those templates. This PR updates the default accordingly.

feat(cli): Make ESM the default for `zapier init` if the template supports it [PDE-6134]

---

packages/core/src/constants.js
packages/core/src/execute-request.js
packages/core/src/execute.js
packages/core/src/http-middlewares/before/inject-input.js
packages/core/src/http-middlewares/before/prepare-request.js
packages/core/src/tools/cleaner.js
packages/core/src/tools/request-merge.js
packages/core/test/create-app.js
packages/core/test/create-request-client.js
packages/core/test/http-middleware.js
packages/core/types/schemas.generated.d.ts
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/test/integration-test.js
packages/legacy-scripting-runner/test/zfactory.js

Changes:
- Internalize the flag that enables/disables `{{curlies}}` replacement in `z.request()`.
- Use a [symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) instead of a property like `req.replace`. This makes it impossible to enable the replacement behavior with `z.request({ replace: true })`.
- Remove `{{curlies}}` support from Raw Requests ([`execute-request.js`](https://github.com/zapier/zapier-platform/blob/2cd98d1a404a7e9acbe1846c25244edb6769f67b/packages/core/src/execute-request.js))
- Disallow multi-pass `{{curlies}}` replacement.
- See test case `should replace curlies in single pass` for what this change is about.
- legacy-scripting-runner's `z.request()` client still needs to keep `{{curlies}}` replacement for backward …

PDE-6149 fix(core): internalize flag that enables/disable `{{curlies}}` replacement, disable `{{curlies}}` for Raw Requests

---

packages/cli/src/utils/build.js

Fixes this warning message when running `zapier build`:

PDE-6151 fix(cli): "Cannot find base config file" tsconfig warning

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/index.js
packages/legacy-scripting-runner/package.json

A quick fix to ensure that, in legacy-scripting-runner 3.8.17 (to be released), `z.request()` will render `{{curlies}}` in different versions of zapier-platform-core.

PDE-6149 fix(legacy-scripting-runner): ensure `z.request()` renders `{{curlies}}` on different core versions

---

packages/core/src/http-middlewares/before/prepare-request.js
packages/core/src/tools/cleaner.js
packages/core/test/constants.js
packages/core/test/create-request-client.js
packages/core/test/http-middleware.js

This PR fixes a regression on v17 where `{{curlies}}` in `requestTemplate` (a property in [`AppSchema`](https://github.com/zapier/zapier-platform/blob/2cd98d1a404a7e9acbe1846c25244edb6769f67b/packages/schema/docs/build/schema.md#appschema)) are no longer rendered. For example, an integration may define:
```
{
requestTemplate: {
headers: {
authorization: 'Bearer {{bundle.authData.access_token}}'
}
}
}
```
Given `bundle.authData.access_token = 'a_token'`:
Expected behavior: Every `z.request()` call automatically includes the header `authorization: Bearer a_token`.
Current behavior in v17 (>=17.0.0 <=17.0.2): `z.request()` throws an error:
```
z.request() no longer supports {{bundle.*}} or {{process.*}} as of v17
```

PDE-6145 fix(core): `{{curlies}}` in `requestTemplate` should be replaced

---

packages/core/src/tools/create-http-patch.js
packages/core/test/tools/create-http-patch.js

Fixes a bug where logged response content sometimes have an unexpected line break.
I found this bug because the test case [`should not cause missing bytes for late listener`](https://github.com/zapier/zapier-platform/blob/542da96acc5a305e6aed786d67d1d953f7615327/packages/core/test/tools/create-http-patch.js#L211) occasionally fails with this error message:
```
1) create http patch
should not cause missing bytes for late listener:
Uncaught AssertionError: expected 4 to equal 46
+ expected - actual
-4
+46
at Assertion.fail (/.../zapier-platform/node_modules/should/cjs/should.js:275:17)
at Assertion.value (/.../zapier-platform/node_modules/should/cjs/should.js:356:19)
at IncomingMessage.<anonymous> (test/tools/create-http-patch.js:294:28)
at IncomingMessage.emit (node:events:530:35)
at …
```

PDE-6176 fix(core): unexpected line break in logged response content

---

packages/core/package.json
yarn.lock

Bump to [latest fernet](https://www.npmjs.com/package/fernet) to resolve
```
node_modules/crypto-js
fernet  <=0.3.1 || >=0.4.0
Depends on vulnerable versions of crypto-js
node_modules/fernet
zapier-platform-core  >=17.2.0
Depends on vulnerable versions of fernet
node_modules/zapier-platform-core 
```

chore(core): PDE-6220 bump fernet to latest

---

packages/core/src/tools/http.js
packages/core/test/tools/create-http-patch.js

Fixes a bug where `text/xml` response content should be logged. We're already logging `application/xml`, but both `text/xml` and `application/xml` should be allowed.

PDE-6249 fix(core): log `text/xml` response content, not just `application/xml`

---

packages/core/types/functions.d.ts
packages/core/types/functions.test-d.ts

By default, polling triggers require an `id` field in the array items they (promise to) return. This restriction can now be overridden by the second type argument to the `PollingTriggerPerform` type, in the case they are not using an `id` field and have specified `primary:true` on one or more output fields.
For example:
```ts
// Good: includes ID.
const perform1 = (async (z, bundle) => {
return [{ id: '1', name: 'test' }];
}) satisfies PollingTriggerPerform;
// Bad, id not returned by default
const perform2 = (async (z, bundle) => {
return [{ itemId: 1, name: 'test' }];
}) satisfies PollingTriggerPerform; // Error!
// Good, non-id return specified with return override.
const perform2 = (async (z, bundle) => {
return [{ itemId: 1, name: 'test' }];
}) satisfies PollingTriggerPerform<B, …
```

chore(core): Allow overriding `id` requirement in polling triggers

---

packages/core/src/tools/fetch-logger.js

This PR defensively handles HTTP responses without the `content-type`.

[PDE-6273] Defensive when content-type is absent

---

packages/cli/src/utils/build.js

This PR re-adds `request-worker` to the bundle built by ESBuild while the warning of `require.resolve` suppressed.

[PDE-6175] request-worker added to bundle while require.resolve warning suppressed

---

packages/cli/src/tests/utils/build.js
packages/cli/src/utils/build.js

Fixes a bug where `zapier build --skip-npm-install` failed to recognize a Lerna monorepo. In which case, it should build the app at the project root rather than the app directory.
For example, for a Lerna monorepo that looks like this:
```
(project root)
lerna.json
package.json
common/
libary-1/
package.json
packages/
app-1/
package.json
...
```
`zapier build --skip-npm-install` should build at the project root instead of `packages/app-1`. When it builds in `packages/app-1`, like it does currently, `common/library-1` will be missing in the output build.zip file.
The fix is simple. We only need to add a few lines to make `looksLikeWorkspaceRoot()` return true when there's a `lerna.json` file.
While I was there, I added test coverage not only for the Lerna case, but also for yarn and pnpm …

PDE-6286 fix(cli): `zapier build` misses local package files when building in a lerna monorepo

---

.github/workflows/ci.yaml
packages/cli/src/constants.js
packages/cli/src/version-store.js

Add support for nodejs22 in `zapier-platform-cli`, I plan to update dependencies to update any EOL packages in another ticket, https://zapierorg.atlassian.net/browse/PDE-6319

BREAKING CHANGE (core): PDE-6283 add nodejs22 support

---

CHANGELOG.md
README.md
changelog/v14-v16.md

Just some housekeeping work on the changelog and docs.
- Move older releases of v14-v16 to the archive.
- Reformat the line ``_released `YYYY-DD-MM`_`` to `_Released YYYY-MM-DD_`. (I always find formatting a date with a code span is a bit strange.)
- "CLI Reference" -> "CLI **Command** Reference" in README.md

PDE-6226 docs: update changelog and docs

---

packages/legacy-scripting-runner/CHANGELOG.md
packages/legacy-scripting-runner/package.json

- :bug: Make `sanitizeHeaders` middleware an optional import ([#1050](https://github.com/zapier/zapier-platform/pull/1050))

PDE-6179 chore(legacy-scripting-runner): release 3.8.18

---

packages/cli/src/oclif/commands/versions.js

https://zapierorg.atlassian.net/browse/PDE-6346
`zapier versions -f json` returns an extra array with three objects, this fixes it so they show what was intended ( error types ). I am questioning if we should remove them all together though? 
```
➜  ZapierWebhookAppCopy zapier versions -f json 
✔ Loading versions
[
{
"Version": "1.0.19",
"Platform": "17.2.0",
"Zap Users": "0",
"State": "private",
"Legacy Date": "",
"Deprecation Date": "null",
"Timestamp": "2025-05-19T13:19:26+00:00"
}
]
[
{},
{},
{}
]
```
Looks like this after this PR ![](https://cdn.zappy.app/13a167469e9bdbb0f798fd352f20c824.png)

fix(cli): PDE-6346 remove empty array at the end of zapier versions -f json

---

packages/cli/src/utils/build.js
packages/cli/src/utils/files.js

When using a Node.js version like v18.15.0 to run `zapier build --debug`, an error can happen:
```
✖ Zipping project and dependencies
oclif:zapier:build TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
oclif:zapier:build     at new NodeError (node:internal/errors:399:5)
oclif:zapier:build     at validateString (node:internal/validators:163:11)
oclif:zapier:build     at Object.join (node:path:1172:7)
oclif:zapier:build     at shouldInclude (/Users/eliang/.asdf/installs/nodejs/18.15.0/lib/node_modules/zapier-platform-cli/src/utils/build.js:164:26)
oclif:zapier:build     at iterfilter (/Users/eliang/.asdf/installs/nodejs/18.15.0/lib/node_modules/zapier-platform-cli/src/utils/itertools.js:15:9)
oclif:zapier:build     at iterfilter.next …
```

PDE-6347 fix(cli): Fix error 'The "path" argument must be of type string' on `zapier build`

---

packages/core/types/schemas.generated.d.ts
packages/schema/docs/build/schema.md
packages/schema/exported-schema.json
packages/schema/lib/schemas/AuthFieldSchema.js

https://zapierorg.atlassian.net/browse/PDE-6397
We split FieldSchema into InputFieldSchema, OutputFieldSchema, and AuthFieldSchema in [v17](https://github.com/zapier/zapier-platform/pull/957/files#diff-371ea404c5803792816e705c11005ffbb6ae594ca64857876e31775c31030370R25) and inadvertently removed the "text" type from AuthFieldSchema, this PR adds it back.

PDE-6397: add text back to authfields

---

packages/core/src/tools/create-logger.js
packages/core/test/logger.js

Currently, we censor every value appearing in `bundle.authData` in the log unless the value [looks like a URL without a secret](https://github.com/zapier/zapier-platform/blob/0784942e39981c33ba35bbc74bb21d86727c96da/packages/core/src/tools/create-logger.js#L151-L153). However, there are many fields in `bundle.authData` that are known to be safe to log uncensored, such as `scope`, `team_id`, and `account`. Censoring them in logs just makes troubleshooting hard.

PDE-5447 fix(core): some authData keys are safe to be logged uncensored

---

packages/cli/docs/cli.md
packages/cli/src/oclif/commands/canary/create.js
packages/cli/src/oclif/commands/canary/list.js
packages/cli/src/utils/api.js

To improve the usability of `zapier canary`, I am looking to add several "audience" type target filters to help isolate canary tests.
The general percentage applies the change to all users, with no way to isolate any problematic invocations to test out a bug fix for instance. 
This PR then aims to add the following filters:
- user (email): to filter by user, can be used with accountId
- accountId: to filter by account

PDE-6289 - Add user and account filters to canary

---

packages/cli/src/oclif/ZapierBaseCommand.js
packages/core/types/schemas.generated.d.ts
packages/schema/docs/build/schema.md
packages/schema/exported-schema.json
packages/schema/lib/schemas/VersionSchema.js

Adds support for `version` in `package.json` that has a label (e.g. `1.2.3-dev`).

feat(schema, cli) Support version with label [PDE-6384]

---

packages/cli/docs/cli.md
packages/cli/src/oclif/commands/pull.js

The description for `zapier pull` is unclear - it indicates it will pull down the latest version, but that is not the case for public apps. Instead, for those, it will pull the production version.

chore(cli): Update `zapier pull` description to clarify it pulls production version, not latest, for public integrations (PDE-6517)

---

packages/cli/docs/cli.md
packages/cli/src/tests/utils/build.js
packages/core/src/http-middlewares/after/prepare-response.js
packages/core/src/tools/create-logger.js
packages/core/src/tools/secret-scrubber.js
packages/core/test/http-middleware.js

To reproduce, use this example trigger and `beforeRequest` middleware:
```js
// Trigger definition
{
key: "recipe",
operation: {
perform: {
url: "https://httpbin.zapier-tooling.com/status/400",
},
},
// ...
}
```
```js
// beforeRequest middleware
const includeAccessToken = (request, z, bundle) => {
if (bundle.authData.access_token) {
request.headers.Authorization = `Bearer ${bundle.authData.access_token}`;
request.params.access_token = bundle.authData.access_token;
}
return request;
};
```
Then run it with `zapier invoke trigger recipe --debug`.
The value of `access_token` is visible in the response error:
```
(redacted)
›   Error: {"status":400,"headers":{"content-type":"text/plain; charset=utf-8","retry-after":null},"content":"","request":{"url":"https://httpbin.zapier-tooling.com/status …
```

PDE-6429 fix(core): censor sensitive info in `ResponseError`

---

packages/cli/docs/cli.md
packages/cli/src/oclif/commands/migrate.js

Reverts the "migrate by action" feature via `zapier migrate --action` (#1126) but keeps some of the minor changes.

PDE-5956: revert(cli): revert `zapier migrate --action` feature

---

packages/core/types/schemas.generated.d.ts
packages/schema/docs/build/schema.md
packages/schema/exported-schema.json
packages/schema/lib/schemas/BasicActionOperationSchema.js
packages/schema/lib/schemas/BasicHookOperationSchema.js
packages/schema/lib/schemas/BasicHookToPollOperationSchema.js
packages/schema/lib/schemas/BasicOperationSchema.js
packages/schema/lib/schemas/BasicPollingOperationSchema.js
packages/schema/lib/schemas/BasicSearchOperationSchema.js
yarn.lock

This pull request adds a new experimental property, `skipCleanArrayInputData `, to operation schemas. This allows users to specify whether Zapier should automatically clean up **array** input data by removing null, undefined, or empty values. 
Schema Files Updated
- Added `skipCleanArrayInputData` to packages/schema/lib/schemas/BasicPollingOperationSchema.js
- Added `skipCleanArrayInputData` to packages/schema/lib/schemas/BasicActionOperationSchema.js
- Added `skipCleanArrayInputData` to packages/schema/lib/schemas/BasicSearchOperationSchema.js
- Added `skipCleanArrayInputData` to packages/schema/lib/schemas/BasicHookOperationSchema.js
- Added `skipCleanArrayInputData` to packages/schema/lib/schemas/BasicHookToPollOperationSchema.js
In the coming major version, we will replace this …

 feat(schema): add skipCleanArrayInputData option to actions ( PDE-6533 )

---

packages/core/types/inputs.d.ts
packages/core/types/inputs.plainfields.test-d.ts
packages/core/types/inputs.test-d.ts

This improves the input field inference so that `bundle.inputData` will be correctly typed for Parent, List, and Dictionary fields. 
Previously, all fields were being considered as "primitive", being one field correlated to one scalar type like `string`, `number`, or `boolean`. This extends the inference to all these types of non-primitive plain inputs to the correct types.
In experimenting with the platform, it was found that `dict` types aren't respected, and will always be strings. See PDE-6547 for further details.
The mental and then typing model of fields had to be expanded. Relevant terms introduced in the inference code are:
- `PlainInputField`: Comes from the schema, any input field that is an object with a `key` field. (therefore is not a field function).
- `ParentInputField`: A …

chore(core): Add Input Field inference for parent, dict, and list fields

---

packages/core/types/inputs.d.ts
packages/core/types/inputs.plainfields.test-d.ts
packages/core/types/inputs.test-d.ts

When `choices` is set, as either an array of strings, array FieldChoiceLabels, or a `Record<string, string>`, the inferred inputData now captures the possible values and pass them through as hints to the `perform` function:
1. Shows the new `StringHints` type derieved from the `Record<string, string>` style `choices` for two of the inputs.
2. Shows hints for relevant values, while allowing other strings, too.
Note that because custom values are permitted, these are treated as hints only, and does not enforce union of a string literal values as a whitelist.

chore(core): Add `choice` field hints to bundle inputs

---

packages/cli/docs/cli.md
packages/cli/src/oclif/commands/migrate.js

PDE-6592 docs(cli): fix incorrect docs in `zapier migrate`

---

packages/core/types/functions.d.ts
packages/core/types/functions.test-d.ts

Followup to https://github.com/zapier/zapier-platform/pull/1166

fix(core): Allow null and undefined values for page_token in SearchResult type

---

packages/core/test/create-app.js
packages/core/test/create-request-client.js
packages/core/test/http-middleware.js
packages/core/test/request-client-internal.js
packages/legacy-scripting-runner/test/integration-test.js

Following up on this [comment](https://github.com/zapier/zapier-platform/pull/1169#issuecomment-3326341774), this PR fixes the failing tests related to HttpBin's `url`.
> Tests are failing because https://httpbin.zapier-tooling.com/get somehow now responds with `url: http://httpbin.zapier-tooling.com/get` instead of `url: https://httpbin.zapier-tooling.com/get` (`http://` vs. `https://`).

PDE-6592 test(core): fix failing tests due to HttpBin URL change

---

packages/cli/package.json
packages/cli/src/utils/api.js
packages/cli/src/utils/credentials.js
packages/cli/src/utils/npm.js
yarn.lock

This is to fix the following `punycode` deprecation warning on Node.js 22+:
```
$ zapier-dev --version
(node:5361) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
* CLI version: 17.7.2
* Node.js version: v22.13.0
* OS info: darwin-arm64
* `zapier-platform-core` dependency: 17.7.2
```
node-fetch 2.7.0 is the culprit. It [depends on whatwg-url](https://github.com/node-fetch/node-fetch/blob/v2.7.0/src/index.js#L23), which in turn, [imports](https://github.com/jsdom/whatwg-url/blob/v5.0.0/src/url-state-machine.js#L2) Node.js's [deprecated `punycode` module](https://nodejs.org/docs/latest-v22.x/api/punycode.html).
Removing node-fetch from the …

PDE-5830 fix(cli): address `punycode` deprecation warning partially by removing `node-fetch`

---

packages/cli/docs/cli.md
packages/cli/src/oclif/commands/push.js
packages/cli/src/utils/api.js
packages/cli/src/utils/build.js

https://zapierorg.atlassian.net/browse/PDE-6609
Zapier push currently takes the package.json version to push to. This makes for a poor DX for creating snapshots because we need to change and then revert. Instead, we can add a option to push to a snapshot label (akin to pushing to a branch that isn't the one you're checked out on in git).

feat(cli) - Add natural snapshot support for zapier push
