- packages/legacy-scripting-runner/bundle.js
- packages/legacy-scripting-runner/test/example-app/index.js
- packages/legacy-scripting-runner/test/integration-test.js
Fixes one of the issues in [PDE-1078](https://zapierorg.atlassian.net/browse/PDE-1078). The test case should be self-explanatory.
> Fix redundant request params when pulling dynamic dropdown

- packages/schema/docs/build/schema.md
- packages/schema/exported-schema.json
- packages/schema/lib/schemas/RefResourceSchema.js
https://github.com/zapier/zapier-platform/pull/48 added support for one comma in a dynamic dropdown, but it looks like we still need to support more than one commas.
> Add support for more than one commas in dynamic dropdown

- packages/legacy-scripting-runner/$.js
- packages/legacy-scripting-runner/test/example-app/index.js
- packages/legacy-scripting-runner/test/integration-test.js
> fix(legacy-scripting-runner): add $.parseJSON to legacy-scripting-runner

- packages/cli/README-source.md
- packages/schema/docs/build/schema.md
fixes #66 by updating all references in the cli to the new repo.
This will get changed again soon as I update the example apps, but it's good to go for now.
> chore(cli) update all links in readme

- docs/index.html
- packages/cli/README-source.md
- packages/cli/README.md
- packages/cli/docs/index.html
There isn't one! Sort of addresses #75
> docs(cli) Clarify difference between apps and integrations

- packages/legacy-scripting-runner/bundle.js
- packages/legacy-scripting-runner/test/bundle.js
- packages/legacy-scripting-runner/test/example-app/index.js
- packages/legacy-scripting-runner/test/integration-test.js
Fixes [PDE-1194](https://zapierorg.atlassian.net/browse/PDE-1194).
> fix(legacy-scripting-runner): add bundle.subscription_url

- packages/cli/src/utils/api.js
This was a regression in 9.0.0 where an app couldn't run `zapier validate` if it had a `.zapierapprc` but not a valid session (as might happen in CLI)
Fixes [PDE-1252](https://zapierorg.atlassian.net/browse/PDE-1252)
> fix(cli): don't require session when validating

- example-apps/typescript/package.json
- yarn.lock
update typescript to latest 3.7.3
update @types/node to latest 10.x
> chore(examples) update typescript to latest 3.7.3

- packages/legacy-scripting-runner/index.js
- packages/legacy-scripting-runner/test/example-app/index.js
- packages/legacy-scripting-runner/test/integration-test.js
Fixes https://github.com/zapier/zapier-platform/issues/138.
> fix(legacy-scripting-runner): handle post_write returning nothing

- packages/legacy-scripting-runner/index.js
- packages/legacy-scripting-runner/test/integration-test.js
> fix(legacy-scripting-runner): overwrite params in authorize URL

- packages/legacy-scripting-runner/$.js
- packages/legacy-scripting-runner/test/example-app/index.js
- packages/legacy-scripting-runner/test/integration-test.js
> feat(legacy-scripting-runner): Add $.extend shim

- packages/cli/src/tests/utils/build.js
Hopefully this is the one last broken piece that blocks releasing.
> fix(cli): fix CLI test circular dependency

- packages/core/smoke-test/smoke-test.js
Hopefully this is the one last broken piece that blocks releasing.
> fix(core): fix smoke test circular dependency

- packages/cli/src/oclif/commands/analytics.js
- packages/cli/src/utils/analytics.js
I just noticed some areas for clarity when I was working on something else.
> improvement(cli): add some light clarity around what we're sending for analytics

- .travis.yml
Hopefully to make Travis run faster.
> ci: enable cache in .travis.yml

- packages/legacy-scripting-runner/bundle.js
- packages/legacy-scripting-runner/test/example-app/index.js
- packages/legacy-scripting-runner/test/integration-test.js
- packages/schema/docs/build/schema.md
Fixes [PDE-1567](https://zapierorg.atlassian.net/browse/PDE-1567).
`bundle.request.data` should be undefined instead of `'{}'` (a string) in `pre_custom_action_fields`.
> fix(legacy-scripting-runner): bundle.request.data should be undefined in pre_custom_action_fields

- docs/index.html
- packages/cli/README-source.md
- packages/cli/README.md
- packages/cli/docs/index.html
- packages/core/index.d.ts
- packages/core/test/userapp/index.js
- packages/schema/docs/build/schema.md
- packages/schema/exported-schema.json
- packages/schema/lib/schemas/BasicActionOperationSchema.js
Adding some more documentation to cover the `z.generateCallbackUrl()` usage.
> docs(core, schema): [CTO-11] Add docs for under documented callback URL feature.

- example-apps/oauth1-trello/test/authentication.test.js
- example-apps/oauth2/test/authentication.test.js
- packages/cli/src/generators/templates/authTests/oauth1.test.js
- packages/cli/src/generators/templates/authTests/oauth2.test.js
> docs(examples): fixing documentation typo (PDE-1821)

- example-apps/session-auth/authentication.js
This will prevent building as the process halts on validation errors.
--- 
_edit by David_
[PDE-1953](https://zapierorg.atlassian.net/browse/PDE-1953)
> fix(cli): Required value must be boolean for authentication field (PDE-1953)

- docs/index.html
- packages/cli/README-source.md
- packages/cli/README.md
- packages/cli/docs/index.html
I missed this alpha designation in my prior PRs on this topic, oops!
> [SUPPORTESC-112] docs(cli): Remove designation of UI>CLI conversion as alpha

- docs/index.html
- packages/cli/README-source.md
- packages/cli/README.md
- packages/cli/docs/index.html
Addresses [PDE-1976](https://zapierorg.atlassian.net/browse/PDE-1976)
> docs(cli): add debugging info to readme

- docs/index.html
- packages/cli/README-source.md
- packages/cli/README.md
- packages/cli/docs/index.html
JIRA: https://zapierorg.atlassian.net/browse/PDE-1994   
Fixes broken link to schema package in the main README.
> PDE-1994  Fix broken README schema package link

- ARCHITECTURE.md
- docs/index.html
- packages/cli/ARCHITECTURE.md
- packages/cli/README-source.md
- packages/cli/README.md
- packages/cli/docs/index.html
- packages/core/ARCHITECTURE.md
- packages/legacy-scripting-runner/ARCHITECTURE.md
- packages/schema/ARCHITECTURE.md
Inspired by https://matklad.github.io/2021/02/06/ARCHITECTURE.md.html, I wanted to write up some files to give new contributors a brief tour of the code.
[PDE-1990](https://zapierorg.atlassian.net/browse/PDE-1990)
> docs (cli, core, schema): add architecture files

- packages/core/src/tools/create-file-stasher.js
- packages/core/test/tools/file-stasher.js
- packages/schema/docs/build/schema.md
- packages/schema/lib/schemas/KeySchema.js
Fixes https://github.com/zapier/zapier-platform/issues/334 | [PDE-2030](https://zapierorg.atlassian.net/browse/PDE-2030)
Also tweaked a schema example because I couldn't remember if dashes were allowed in keys (they're not!)
> fix(core): handle stashing files in resource create methods

- example-apps/session-auth/authentication.js
> PDE-2180: fix(example): minor typo in authentication.js

- packages/core/src/checks/trigger-has-unique-ids.js
- packages/core/test/checks.js
fixes [PDE-2361](https://zapierorg.atlassian.net/browse/PDE-2361)
> fix(core): checks should properly handle possibly null values

- docs/index.html
- packages/cli/README.md
- packages/cli/docs/index.html
- packages/cli/snippets/dynamic-dropdowns-six.js
Fix an incorrect integration definition.
> [PDE-2423] Trigger has no key of create.

- docs/cli.html
- docs/index.html
- docs/template.jst
- packages/cli/docs/cli.html
- packages/cli/docs/index.html
- packages/cli/docs/template.jst
The change itself was made in the .jst files and copied over during pre-commit.
[PDE-2300](https://zapierorg.atlassian.net/browse/PDE-2300)
> docs(cli): update GA tag

- docs/index.html
- packages/cli/README-source.md
- packages/cli/README.md
- packages/cli/docs/index.html
- packages/schema/docs/build/schema.md
I had noticed the phrase "is kind of like" in comparing these two and wanted to give a bit more context on differences - so added another type of processing done on raw input and related examples.
Very open to changes if there's more detail I should add, or a better way to present this!
It looks like the pre-commit processing also generated a lot of schema changes, which aren't part of the the work I did, but seem to be mostly formatting details, so hopefully not a problem. I tried making sure I was on the latest version of everything, but the changes persisted.
> [SUPPORTESC-192] docs(cli): A bit more detail around inputData and inputDataRaw

- package.json
- packages/cli/src/smoke-tests/smoke-tests.js
- packages/core/src/tools/create-http-patch.js
- packages/core/src/tools/create-lambda-handler.js
- packages/core/src/tools/create-logger.js
- packages/core/test/logger.js
- packages/core/test/tools/mocky.js
- yarn.lock
> PDE-2650 perf(core): improve logging performance (9.x backport)

- packages/core/integration-test/integration-test.js
- packages/core/src/tools/create-logger.js
- packages/core/test/create-request-client.js
- packages/core/test/tools/mocky.js
- packages/core/test/userapp/index.js
> fix(core): fix another scenario that causes hanging (9.x)

- docs/index.html
- packages/cli/README-source.md
- packages/cli/README.md
- packages/cli/docs/index.html
- packages/cli/snippets/jest-adhoc-func.js
- packages/cli/snippets/jest-mocked-test.js
- packages/cli/snippets/jest-test.js
* Confirmed all hyperlinks work and direct to the correct location
* Just a few minor wording changes here and there; no major changes.
> [PDE-3149] Update README's "Testing" section with minor changes

- docs/index.html
- packages/cli/README-source.md
- packages/cli/README.md
- packages/cli/docs/index.html
- packages/cli/snippets/manual-request.js
- packages/cli/snippets/shorthand-request.js
part of q1 2022 hack week. https://coda.io/d/HackWeek-2022-Q1_d_CnAb9OV3_/Improve-Dev-Platform-Docs_susOs#Focus-Areas_tuTH1/r34
This PR includes various doc improvements with the main focus on the "Making HTTP Requests" section
> [PDE-3149] Update Making HTTP Requests section

- docs/cli.html
- docs/cli.md
- packages/cli/docs/cli.html
- packages/cli/docs/cli.md
- packages/cli/src/oclif/commands/team/add.js
- packages/cli/src/oclif/commands/team/get.js
- packages/cli/src/oclif/commands/team/remove.js
- packages/cli/src/utils/team.js
JIRA: https://zapierorg.atlassian.net/browse/PDE-3159
Adds a new role to be deletable with the `team:remove` command
> PDE-3159 feat(cli): Add collaborator to `team:remove` command

- packages/core/src/tools/create-logger.js
- packages/core/src/tools/data.js
- packages/core/test/fixtures/truncate-test-data.json
- packages/core/test/misc-tools.js
Optimizes the logging to only scrub secrets on data that gets logged (we cap log fields at 3500 characters), maintaining JSON structure. Cuts logging time for large objects in half or more!
> CRIT-371 perf(core): Optimize secret-scrubbing input in logger

- packages/cli/src/utils/build.js
fix(cli): Follow-up to https://github.com/zapier/zapier-platform/pull/573 to fix the failing LINT
> [PDE-3393] Fix failing LINT

- CHANGELOG.md
> PDE-3411 docs: update 12.1.0 changelog to be more clear

- packages/cli/README.md
> PDE-2828 chore: Fix typo accont

- packages/cli/src/oclif/commands/promote.js
- packages/cli/src/tests/utils/check-missing-app-info.js
- packages/cli/src/utils/build.js
- packages/cli/src/utils/check-missing-app-info.js
> [PDE-3678] Block promote, upload, and push for missing required app info

- docs/index.html
- packages/cli/README-source.md
- packages/cli/README.md
- packages/cli/docs/index.html
Updating throttling text in CLI README to include detail from https://zapierorg.atlassian.net/browse/AP-1927
> SUPPORTENG_560_throttling_edits

- docs/index.html
- packages/cli/README-source.md
- packages/cli/README.md
- packages/cli/docs/index.html
> PDE-3940-update-expiredAuthError

- example-apps/typescript/package.json
- packages/cli/src/tests/utils/build.js
- packages/core/index.d.ts
Fixes failing tests in #646.
@kola-er if it looks good to you, you can merge it or manually copy the changes to your branch, whichever suits you best!
> PDE-3832 fix(test): fix failing tests

- docs/index.html
- packages/cli/README-source.md
- packages/cli/README.md
- packages/cli/docs/index.html
> SUPPORTENG-508_hydration_payload_limit

- docs/index.html
- packages/cli/README.md
- packages/cli/docs/index.html
- packages/cli/src/constants.js
- packages/cli/src/oclif/commands/promote.js
- packages/cli/src/tests/utils/changelog.js
- packages/cli/src/utils/changelog.js
- packages/cli/src/utils/metadata.js
This requires that a changelog is present, as well as supporting providing additional metadata about the release to bring feature parity with the Dev Platform UI.
> Support providing additional contextual metadata in a changelog

- example-apps/babel/README.md
- example-apps/create/README.md
- example-apps/middleware/README.md
- example-apps/oauth1-twitter/README.md
- example-apps/onedrive/README.md
- example-apps/resource/README.md
- example-apps/rest-hooks/README.md
- example-apps/search/README.md
Discussed here: https://zapier.slack.com/archives/C04P5J5R8E4/p1687815849325469
> SUPPORTENG-918_example_apps_edits

- packages/cli/README-source.md
as discussed https://zapier.slack.com/archives/C04P5J5R8E4/p1687815849325469
> SUPPORTENG-918_update_example_apps_template_reference

- docs/cli.html
- docs/cli.md
- packages/cli/docs/cli.html
- packages/cli/docs/cli.md
- packages/legacy-scripting-runner/test/example-app/index.js
> PDE-0 - fix(legacy-scripting-runner) legacy scripting runner test

- packages/schema/docs/build/schema.md
- packages/schema/exported-schema.json
- packages/schema/lib/schemas/BasicHookOperationSchema.js
- packages/schema/lib/schemas/BasicPollingOperationSchema.js
Follow-up to https://github.com/zapier/zapier-platform/pull/709.
> feat(schema): Allow setting throttle configuration on triggers

- packages/cli/README.md
> docs(cli):Fix broken link in readme.md

- example-apps/rest-hooks/triggers/recipe.js
Updating rest hook tutorial to include content for expiring webhooks.
> UDOCS-1631 - expiring subscriptions content

- docs/index.html
- packages/cli/README-source.md
- packages/cli/README.md
- packages/cli/docs/index.html
Documenting 5min cache behavior of hydration and how to workaround.
Raised in thread https://zapier.slack.com/archives/C04P5J5R8E4/p1706544733342789?thread_ts=1706524851.992879&cid=C04P5J5R8E4Connect your Slack account  and ticket https://zapier.zendesk.com/agent/tickets/1801009
> PLATSUP-1015_Hydration_5min_cache

- example-apps/custom-auth/authentication.js
Not sure if this provides you any value - feel free to close if not :-)
> docs(examples): Avoid a warning from zapier cli when using the custom-auth sample

- docs/index.html
- packages/cli/README-source.md
- packages/cli/README.md
- packages/cli/docs/index.html
> docs(cli): document `primary` in `outputFields`

- packages/core/src/tools/create-logger.js
- packages/core/test/logger.js
When invoking methods like `authentication.sessionConfig.perform` or `authentication.oauth2Config.refreshAccessToken`, some servers would just return the new token as a JSON string in the response content. This patch fixes the issue where the new token is not censored in the HTTP log.
> PDE-4683 core(fix): censor entire response content when getting new secret

- docs/index.html
- packages/cli/README-source.md
- packages/cli/README.md
- packages/cli/docs/index.html
Add in subdomain validation recommendation in the Authentication sub heading
> PLATSUP-1048-CLI subdomain validation

- packages/cli/README-source.md
Reverts zapier/zapier-platform#800
> Revert "docs(core) Document performResume default implementation."

- packages/core/src/app-middlewares/after/large-response-cacher.js
- packages/core/test/app-middleware.js
Checks if output.results is truthy before attempting to cache
> PDE-5158 fix(core) - Fix afterApp large response cacher bug

- packages/cli/src/tests/utils/changelog.js
- packages/cli/src/utils/changelog.js
Hi,
This is a simple attempt to add support for the 'Keep a Changelog' format (https://keepachangelog.com). It is a popular changelog format, and the current parser returns an error if someone wants to use it.
> feat(cli): Handle subheadings when interpreting the changelog

- packages/core/src/tools/create-rpc-client.js
- packages/core/test/tools/rpc-client.js
> feat(core) - Retry on 5xx errors

- CHANGELOG.md
> PDE-5460 docs: update links in changelog

- packages/cli/src/utils/build.js
- packages/cli/src/utils/local.js
Fix for this issue: https://github.com/zapier/zapier-platform/issues/1019
> PDE-6136 - fix(cli) - Fix Path for windows

- packages/cli/docs/cli.md
- packages/cli/src/oclif/commands/deprecate.js
Documents the changes in https://gitlab.com/zapier/zapier/-/merge_requests/63502
> docs(cli) [PDE-6238] Update CLI Docs for new days before deprecation and sending emails

- packages/core/src/tools/create-rpc-client.js
Add better error message when RPC returns 413 Request Entity too large.
> feat(core) PDE-6475: add better error message for 413

- packages/core/src/checks/search-is-array-or-envelope.js
- packages/core/test/checks.js
> core(fix): Allow paging_token with undefined as a value
